<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');

$customerSession = $block->customerSession;
$customerRepository = $block->customerRepository;
$application_verified_status = false;
$shortdatedFlag = false;
$storeShortDatedGroupIds = $block->getConfigValue('drd_short_dated/drd_short_dated_group/customer_group_id');
//echo $storeShortDatedGroupIds;die;
if(!empty($storeShortDatedGroupIds) || !$storeShortDatedGroupIds){
    $storeShortDatedGroupIds = explode(',', $storeShortDatedGroupIds);
    if(in_array(0, $storeShortDatedGroupIds)){
        $shortdatedFlag = true;
    }
}
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">

                    <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                        <?php if(($_product->getTypeId() == 'simple') && ($shortdatedFlag)) { ?>
                            <?php
                                $categorytype_string = $_product->getResource()->getAttribute('categorytype')->getFrontend()->getValue($_product);
                                $categorytype_array = explode(', ', $categorytype_string);
                                //echo '<pre>'.print_r($categorytype_array, true).'.</pre>';
                            ?>
                            <?php if(in_array('Special buy', $categorytype_array)){ ?>
                                <div class="drl-short-dated">
                                    <span class="label-short-dated"><?= $block->escapeHtml(__('Short Dated Available')) ?></span>
                                </div>
                            <?php } ?>
                        <?php } else { ?>
                                <div class="drl-short-dated" id="ajax-short-dated-<?php echo $_product->getId(); ?>" style="display:none">
                                    <span class="label-short-dated"><?= $block->escapeHtml(__('Short Dated Available')) ?></span>
                                </div>
                        <?php } ?>
                        <?php if($block->getIsApproved()){ ?>
                            <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                            <?php endif; ?>
                        <?php } ?>
                    </div>

                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <?php
                        $_productNameLength = strlen($_helper->productAttribute($_product, $_product->getName(), 'name'));

                        if($_productNameLength < 57){
                            $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                        } else {
                            $_productName = substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 55).'...';
                        }

                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link ajax-product-item-name-<?php echo $_product->getId(); ?>" title="<?= /* @noEscape */ $_productNameStripped; ?>"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_productName; ?>
                            </a>
                        </strong>
                        <div class="drl-sku-cashback-attribute"><?= $block->escapeHtml(__('NDC #:')) ?> <span class="drl-sku-product product-attribute-sku-<?php echo $_product->getId(); ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?></span><br />
                        </div>
                        <?php if($block->getIsApproved()){ ?>
                            <div class="drl-sku-cashback-attribute-second">
                                <span class="product-available-stock drl-cashback-stock">
                                    Packs Available: <span id="product-available-qty-value-<?php echo $_product->getSku(); ?>">
                                    <?php echo $StockState->execute($_product->getSku(), $_product->getStore()->getWebsiteId());?></span>
                                </span>
                            </div>
                        <?php } ?>
                        <?php if($_helper->productAttribute($_product, $_product->getStrength(), 'strength')) { ?>
                            <div class="drl-sku-cashback-attribute-seconds">
                                <div class="attribute-pack-size">
                                    <div class="swatch-attribute pack_size" >
                                        <span class="swatch-attribute-label">Total Content: </span>
                                        <span class="swatch-attribute-value"><?php echo $_product->getResource()->getAttribute('strength')->setStoreId(0)->getFrontend()->getValue($_product); ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <?php if($_helper->productAttribute($_product, $_product->getPackSize(), 'pack_size')) { ?>
                            <div class="drl-sku-cashback-attribute-second">
                                <span class="swatch-attribute-label">Pack Size</span>
                                <div class="drl-attribute-strength">
                                    <?php echo $_product->getResource()->getAttribute('pack_size')->setStoreId(0)->getFrontend()->getValue($_product); ?>
                                </div>
                            </div>
                        <?php } ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>

                        <div class="product-price">
                            <?php if ($_product->getPriceInfo()->getPrice('final_price')->getValue() != 0) { ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php } ?>
                        </div>
                        <div class="product-item-inner">
                            <?php if($block->getIsApproved()){ ?>
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <?php if ($_product->isSaleable()) :?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                                      action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                        <?php else :?>
                                            <?php if ($_product->isAvailable()) :?>
                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else :?>
                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php } ?>

                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
