<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $block->getOrder() ?>
<div class="actions-toolbar">
    <a href="<?= $block->escapeUrl($block->getPrintAllInvoicesUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $block->escapeHtml(__('Print All Invoices')) ?></span>
    </a>
</div>
<?php foreach ($_order->getInvoiceCollection() as $_invoice) : ?>
    <?= $block->getInvoiceCommentsHtml($_invoice) ?>
    <div class="order-title">
        <?php if($block->getSapInvoiceId($_invoice->getId())){ ?>
            <strong><?= $block->escapeHtml(__('Invoice #')) ?> <?= $block->escapeHtml($block->getSapInvoiceId($_invoice->getId())) ?></strong>
        <?php } else { ?>
            <strong><?= $block->escapeHtml(__('Invoice #')) ?> <?= $block->escapeHtml($_invoice->getIncrementId()) ?></strong>
        <?php } ?>
        <?php if($_invoice->getState() == 1){ ?>
            (Pending)
        <?php } else if($_invoice->getState() == 2) { ?>
            (Paid)
        <?php } else if($_invoice->getState() == 3) { ?>
            (Canceled)
        <?php } ?>
        <a href="<?= $block->escapeUrl($block->getPrintInvoiceUrl($_invoice)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print Invoice')) ?></span>
        </a>
    </div>
    <div class="table-wrapper table-order-items invoice">
        <table class="data table table-order-items invoice" id="my-invoice-table-<?= (int) $_invoice->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Invoiced')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                    <th class="col price"><?= $block->escapeHtml(__('Price Type')) ?></th>
                    <th class="col qty"><?= $block->escapeHtml(__('Qty Invoiced')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Discount')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Total')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_invoice->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
            <tfoot>
                <?= $block->getInvoiceTotalsHtml($_invoice) ?>
            </tfoot>
        </table>
    </div>
<?php endforeach; ?>
