<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
    $_productCollection = $block->getLoadedProductCollection();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?=$escaper->escapeHtml(__('We can\'t find products matching the selection.'))?></div>
    </div>
    <?php else: ?>
        <?php 
        $listBlock= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
        $viewModel = $block->getData('view_model');
        /** @var \Magento\Catalog\Helper\Output $_helper */
        $_helper = $block->getData('outputHelper');
        $custom_helper = $this->helper('Ecomm\Theme\Helper\Output');
        //$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        //$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
        $StockState = $listBlock->getSalableQuantityDataBySku;
        // $StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
        // $StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
        //$customerSession = $objectManager->create('Magento\Customer\Model\Session');
        $customerSession = $listBlock->customerSession;
        //echo "<pre>";print_r($customerSession->getId());die;
        //$customerRepository = $objectManager->get('\Magento\Customer\Api\CustomerRepositoryInterface');
        $customerRepository = $listBlock->customerRepository;

        $application_verified_status = false;
        $shortdatedFlag = false;
        if ($customerSession->isLoggedIn()) {
            //$_eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
            $_eavConfig = $listBlock->eavConfig;

            if ($customerSession->getId()) {
                $customerData = $customerRepository->getById($customerSession->getId());
                /* Code to set DRD Short Data Flag Start */
                $customerGroupId = $customerData->getGroupId();
                $storeShortDatedGroupIds = $block->getConfigValue('drd_short_dated/drd_short_dated_group/customer_group_id');
                //echo $storeShortDatedGroupIds;die;
                if(!empty($storeShortDatedGroupIds) || (!$storeShortDatedGroupIds)){
                    $storeShortDatedGroupIds = explode(',', $storeShortDatedGroupIds);
                }
                if(in_array($customerGroupId, $storeShortDatedGroupIds)){
                    $shortdatedFlag = true;
                }
                /* Code to set DRD Short Data Flag End */
                $attribute = $_eavConfig->getAttribute('customer', 'application_status');
                $options = $attribute->getSource()->getAllOptions();
                $application_statuses = [];
                foreach ($options as $option) {
                    if ($option['value'] > 0) {
                       $application_statuses[$option['value']] = $option['label'];
                    }
                }
                $application_status = 0;
                $approved_id = array_search("Approved", $application_statuses);
                if ($customerData->getCustomAttribute('application_status')) {
                    $application_status = $customerData->getCustomAttribute('application_status')->getValue();
                }

                if ($approved_id == $application_status) {
                    $application_verified_status = true;
                }
            }
        }
        ?>
        <?=$block->getToolbarHtml()?>
        <?=$block->getAdditionalHtml()?>
    <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
?>

        <div class="products wrapper <?=/* @noEscape */$viewMode?> products-<?=/* @noEscape */$viewMode?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */?>
                <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $blockObj = $block->getLayout()->createBlock('Ecomm\HinEligibilityCheck\Block\exclusivePrice');
                    $priceLogicBlock = $block->getLayout()->createBlock('Ecomm\PriceEngine\Block\CustomPriceLogic');
                    $exclusivePriceMethod = $blockObj->getCollection();
                    $addressRepo = $blockObj->getAddressCollection();
                    $customerId = $priceLogicBlock->getCustomerId();
                    $customerGroupId = $priceLogicBlock->getCustomerGroupId();
                    $product_sku = $_product->getSku();
                    if($customerId){
                        $customerInfo = $customerRepository->getById($customerSession->getId());
                ?>
                <!--getting default shipping address details -->
                <?php
                        $shippingAddressId = $customerInfo->getDefaultShipping();
                        $addressInfo = $addressRepo->getById($shippingAddressId);
                        if ($addressInfo->getCustomAttribute('hin_status') != null) {
                            $hinStatus = $addressInfo->getCustomAttribute('hin_status')->getValue();
                        } else {
                            $hinStatus = '';
                        }
                    } else {
                        $hinStatus = '';
                    }       
                    $getstate = $this->getRequest()->getParams('state');
                    $showblock = 1;

                    if (isset($getstate['state']) && $getstate['state'] == 'stock') {
                        $stockstatus = $custom_helper->getConfigVal('cataloginventory/options/display_product_stock_status');
                        if ($stockstatus) {
                            /*Checking the whether instock or out of stock*/
                            $stockval = $custom_helper->getStockCheck($_product->getSku(), $_product->getId());
                            $instock = $stockval['instock'];
                            $custominstock = $stockval['custominstock'];
                            if ($instock || $custominstock) {
                                $showblock = 1;
                            } else {
                                $showblock = 0;
                            }
                        }
                    }
                    if ($showblock) {
                    ?>
                        <li class="item product product-item">
                            <div class="product-item-info"
                                id="product-item-info_<?=/* @noEscape */$_product->getId()?>"
                                data-container="product-<?=/* @noEscape */$viewMode?>">
                                <?=strpos($pos, $viewMode . '-primary') ?
                                /* @noEscape */$secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                ) : ''?>
                                <div data-role="add-to-links" class="actions-secondary">
                                        <?php if (($_product->getTypeId() == 'simple') && ($shortdatedFlag)) {
                                            $categorytype_string = $_product->getResource()->getAttribute('categorytype')->getFrontend()->getValue($_product);
                                            $categorytype_array = explode(', ', $categorytype_string);
                                            //echo '<pre>'.print_r($categorytype_array, true).'.</pre>';
                                             if (in_array('Special buy', $categorytype_array)) {?>
                                                <div class="drl-short-dated">
                                                    <span class="label-short-dated"><?= $block->escapeHtml(__('Short Dated Available')) ?></span>
                                                </div>
                                        <?php 
                                            }
                                        } else {
                                            /*
                                        ?>
                                            <div class="drl-short-dated" id="ajax-short-dated-<?php echo $_product->getId(); ?>" style="display:none">
                                                <span class="label-short-dated"><?= $block->escapeHtml(__('Short Dated Available')) ?></span>
                                            </div>
                                    <?php 
                                        */
                                        }
                                        if ($application_verified_status) {
                                    ?>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?=$addToBlock->setProduct($_product)->getChildHtml()?>
                                        <?php endif;?>
                                    <?php } ?>
                                </div>
                                <?=strpos($pos, $viewMode . '-secondary') ?
                                /* @noEscape */$secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                ) : ''?>

                                <?php
                                $productImage = $block->getImage($_product, $imageDisplayArea);
                                if ($pos != null) {
                                    $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?=$escaper->escapeUrl($_product->getProductUrl())?>"
                                   class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?=$productImage->toHtml()?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true);?>
                                    <?php
                                    $_productNameLength = strlen($_helper->productAttribute($_product, $_product->getName(), 'name'));

                                    if ($_productNameLength < 57) {
                                        $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                                    } else {
                                        $_productName = substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 55) . '...';
                                    }
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link ajax-product-item-name-<?php echo $_product->getId(); ?>" title="<?=/* @noEscape */$_productNameStripped;?>"
                                           href="<?=$escaper->escapeUrl($_product->getProductUrl())?>">
                                            <?=/* @noEscape */$_productName;?>
                                        </a>
                                    </strong>
                                    <div class="drl-sku-cashback-attribute">NDC #: <span class="drl-sku-product product-attribute-sku-<?php echo $_product->getId(); ?>"><?=/* @noEscape */$_helper->productAttribute($_product, $_product->getSku(), 'sku')?></span><br />
                                    </div>
                                    <?php if ($application_verified_status) {
                                            if ($_product->getTypeId() == 'simple') {
                                                $salable_quantities = $StockState->execute($_product->getSku());
                                            }
                                        ?>
                                        <div class="drl-sku-cashback-attribute-second">
                                                <!--<span class="product-available-stock drl-cashback-stock">
                                                Packs Available: <span id="product-available-qty-value-<?php /*echo $_product->getId();*/?>">
                                                <?php /*if($_product->getTypeId() == 'simple') {
                                                $salable_quantities = $StockState->execute($_product->getSku());
                                                echo $salable_quantities[0]['qty'];
                                                }*/?></span>
                                                </span>-->
                                            <?php
                                            $stockstatus = $custom_helper->getConfigVal('cataloginventory/options/display_product_stock_status');
                                            if ($stockstatus) {
                                                /*Checking the whether instock or out of stock*/
                                                $stockval = $custom_helper->getStockCheck($_product->getSku(), $_product->getId());
                                                $instock = $stockval['instock'];
                                                $custominstock = $stockval['custominstock'];
                                                $_productStock = $custom_helper->getStockItem($_product->getId());
                                                //echo $instock.' - '.$_productStock->getQty().' - '.$custominstock;
                                                if ($instock || $custominstock) {?>
                                                    <div class="stock stock-available">
                                                        <span><?=$escaper->escapeHtml(__('In stock'))?></span>
                                                    </div>
                                                <?php } else {?>
                                                    <div class="stock stock-unavailable">
                                                        <span><?=$escaper->escapeHtml(__('Out of stock'))?></span>
                                                    </div>
                                            <?php 
                                                }
                                            }
                                            ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($_helper->productAttribute($_product, $_product->getStrength(), 'strength')) { ?>
                                        <div class="drl-sku-cashback-attribute-seconds">
                                            <div class="attribute-pack-size">
                                                <div class="swatch-attribute pack_size" >
                                                    <span class="swatch-attribute-label">Total Content: </span>
                                                    <span class="swatch-attribute-value"><?php echo $_product->getResource()->getAttribute('strength')->setStoreId(0)->getFrontend()->getValue($_product); ?></span>
                                                </div>
                                            </div>
                                        </div>
                                    <?php }?>
                                    <?php if ($_helper->productAttribute($_product, $_product->getPackSize(), 'pack_size')) { ?>
                                        <div class="drl-sku-cashback-attribute-second">
                                            <span class="swatch-attribute-label">Pack Size</span>
                                            <div class="drl-attribute-strength">
                                                <?php echo $_product->getResource()->getAttribute('pack_size')->setStoreId(0)->getFrontend()->getValue($_product); ?>
                                            </div>
                                        </div>
                                    <?php }?>
                                    <?=$block->getReviewsSummaryHtml($_product, $templateType)?>
                                    <?php if ($_product->isAvailable()): ?>
                                        <?=$block->getProductDetailsHtml($_product)?>
                                    <?php endif;?>
                                    <?php $price = array();?>
                                    <?php 
                                        if($customerId){
                                            $regularprice = $priceLogicBlock->getCustomRegularPrice($customerId,$_product);
                                            $price[]=$regularprice['price'];
                                        }
                                    ?>

                                    <?php if ($hinStatus == "1") {
                                        $subWac = $priceLogicBlock->get340bPrice('sub_wac',$_product);

                                        // $subWac = $_product->getResource()->getAttribute('sub_wac')->setStoreId(0)->getFrontend()->getValue($_product);
                                        if (isset($subWac['price'])) {
                                            $price[] = $subWac['price'];
                                        }
                                        $phsIndirect = $priceLogicBlock->get340bPrice('phs_indirect',$_product);

                                        // $phsIndirect = $_product->getResource()->getAttribute('phs_indirect')->setStoreId(0)->getFrontend()->getValue($_product);

                                        if (isset($phsIndirect['price'])) {
                                            $price[] = $phsIndirect['price'];
                                        }
                                        $finalPrice = array();
                                        foreach ($price as $prices) {
                                            if ($prices == 0) {
                                                continue;
                                            } else {
                                                $finalPrice[] = $prices;
                                            }
                                        }

                                    } else {
                                        $finalPrice = array();
                                        foreach ($price as $prices) {
                                            if ($prices == 0) {
                                                continue;
                                            } else {
                                                $finalPrice[] = $prices;
                                            }
                                        }
                                    }?>

                                    <div class="product-price">
                                        <?php if (isset($finalPrice) && $finalPrice != null) {?>
                                            <div class="price-box price-final_price" data-role="priceBox">
                                                <p class="prp-price"><span class="prp-min-price"><?='$' . number_format(min($finalPrice), 2);?></span> - <span class="prp-max-price"><?='$' . number_format(max($finalPrice), 2);?></span></p>
                                                <p class="plp-view-para" ><a href="<?=$escaper->escapeUrl($_product->getProductUrl())?>" class="plp-view-dtl">View Details</a></p>
                                            </div>
                                        <?php } else {?>
                                            <div class="price-box price-final_price" data-role="priceBox">
                                                <p class="plp-view-para" ><a href="<?=$escaper->escapeUrl($_product->getProductUrl())?>" class="plp-view-dtl">View Details</a></p>
                                            </div>
                                        <?php }?>
                                    </div>
                                    <div class="product-item-inner">
                                        <?php if ($_product->getTypeId() == 'configurable') {
                                            if ($application_verified_status) { ?>
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-primary">
                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_product);?>
                                                            <form data-role="tocart-form"
                                                                data-product-sku="<?=$escaper->escapeHtml($_product->getSku())?>"
                                                                action="<?=$escaper->escapeUrl($postParams['action'])?>"
                                                                method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
                                                                <input type="hidden"
                                                                    name="product"
                                                                    value="<?=/* @noEscape */$postParams['data']['product']?>">
                                                                <input type="hidden"
                                                                    name="<?=/* @noEscape */Action::PARAM_NAME_URL_ENCODED?>"
                                                                    value="<?=
                                                                    /* @noEscape */$postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                                ?>">
                                                                <?=$block->getBlockHtml('formkey')?>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_product->isAvailable()): ?>
                                                                <div class="stock available">
                                                                    <span><?=$escaper->escapeHtml(__('In stock'))?></span>
                                                                </div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                    <span><?=$escaper->escapeHtml(__('Out of stock'))?></span>
                                                                </div>
                                                            <?php endif;?>
                                                        <?php endif;?>
                                                    </div>
                                                </div>
                                            <?php }?>
                                        <?php } else { ?>
                                            <?php if (($application_verified_status) && (isset($salable_quantities[0]['qty']) && $salable_quantities[0]['qty'] > 0) && $_productStock->getQty() > 0) { ?>
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-primary">
                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_product);?>
                                                            <?php if (min($price) != 0 && max($price) != 0) { ?>
                                                                <form data-role="tocart-form"
                                                                    data-product-sku="<?=$escaper->escapeHtml($_product->getSku())?>"
                                                                    action="<?=$escaper->escapeUrl($postParams['action'])?>"
                                                                    method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
                                                                    <input type="hidden"
                                                                        name="product"
                                                                        value="<?=/* @noEscape */$postParams['data']['product']?>">
                                                                    <input type="hidden"
                                                                        name="<?=/* @noEscape */Action::PARAM_NAME_URL_ENCODED?>"
                                                                        value="<?=
                                                                        /* @noEscape */$postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                                    ?>">
                                                                    <?=$block->getBlockHtml('formkey')?>
                                                                </form>
                                                            <?php } ?>
                                                        <?php else: ?>
                                                            <?php if ($_product->isAvailable()): ?>
                                                                <div class="stock available">
                                                                    <span><?=$escaper->escapeHtml(__('In stock'))?></span>
                                                                </div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                    <span><?=$escaper->escapeHtml(__('Out of stock'))?></span>
                                                                </div>
                                                            <?php endif;?>
                                                        <?php endif;?>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                        <?php } ?>
                                        <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                                <?=/* @noEscape */$_helper->productAttribute(
                                                $_product,
                                                $_product->getShortDescription(),
                                                'short_description'
                                                )?>
                                                <a href="<?=$escaper->escapeUrl($_product->getProductUrl())?>"
                                                   title="<?=/* @noEscape */$_productNameStripped?>"
                                                   class="action more"><?=$escaper->escapeHtml(__('Learn More'))?></a>
                                            </div>
                                        <?php endif;?>
                                    </div>
                                </div>
                            </div>
                            <?=strpos($pos, $viewMode . '-actions') ?
                            /* @noEscape */$secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                            ) : ''?>
                        </li>
                    <?php } ?>
                <?php endforeach;?>
            </ol>
    </div>
    <?=$block->getToolbarHtml()?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?=$escaper->escapeJs($_product->getSku())?>"
                }
            }
        }
        </script>
    <?php endif;?>
<?php endif;?>
