<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="block block-customer-login-container">

    <div class="cus-title">
       <strong class="cus-login-title">   <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/Logo-reg-for-d.png'); ?>' alt="customer-icon" width="150" height="33"> </strong>
   </div>

   <div class="cus-title-below">
      <span class="cus-login-title-below"> Welcome to <span class="cus-log-tlt-sec"> Dr.Reddy’s Direct! </span> </span>
   </div>

 <?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('news_scroll')
->toHtml();
?>

</div>

<div class="block block-customer-login customer-login-outer">

  <div  class="block-customer-login-inner">

    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Login')) ?></strong>
    </div>
    <div class="block-content customer-login-inner" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
              <!--  <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div> -->
                <div class="field email customer-login-email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Company Email ID')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text customer-login-input" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="Enter Company Email">
                    </div>
                </div>
                <div class="field password  customer-login-password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text customer-login-input" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" placeholder="Enter Password">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar customer-login-checbox">
                    <!-- <div class="primary form-group"> 
                            <input type="checkbox" id="remember">
                            <label for="remember">Remember</label>
                    </div> -->
                    <div class="secondary form-forget"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>

                <div class="actions-toolbar">
                     <div class="customer-login-button"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button></div>                    
                </div>

                <div class="actions-toolbar">
                     <div class="customer-dont-account"><span class="customer-d-acc">Don't have an account ?</span><span class="customer-d-signup"><a href="<?php echo $this->getUrl('register-landing-page') ?>">Sign Up</a></span></div>                    
                </div>

            </fieldset>
        </form>
    </div>

  </div>

    <div class="block-content-under">         

        <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/login-bottom.png'); ?>' alt="image-icon" width="30" height="25">

    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                }
            }
        }
    </script>

</div>

