<?php $items = $block->getProducts() ?>
<table class="email-items">
    <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */  __('NDC'); ?>
            </th>
            <th class="item-qty">
                <?= /* @escapeNotVerified */  __('Product Name'); ?>
            </th>
            <!-- <th class="item-price">
                <?= /* @escapeNotVerified */  __('Price Type'); ?>
            </th> -->
        </tr>
    </thead>
    <tbody>
    <?php $productId = array(); ?>
    <?php foreach ($items as $item): ?>
        <?php 
            if(!isset($productId[$item['product_sku']])){ 
                $productId[$item['product_sku']] = $item['product_sku'];
        ?>
            <tr>
                <td><?= $item['product_sku'] ?></td>
                <td><?= $item['product_name'] ?></td>
                <!-- <td><?= $item['product_price_type'] ?></td> -->
            </tr>
        <?php } ?>
    <?php endforeach; ?>
    </tbody>
</table>