<?php if ($block->getIsApproved()) { ?>
	<li class="quickorder_link">
		<a class="drl-quick-order" <?php echo $block->getLinkAttributes() ?>><?php echo $block->escapeHtml($block->getLabel()) ?>
			<?php echo ($block->getCounter()) ? '<span>' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>
		</a>
	</li>
	<li class="link wishlist mobile-view-drl">
		<a href="<?php echo $block->getUrl('checkout/cart/') ?>">My Cart</a>
	</li>
	<li class="link notification mobile-view-drl">
		<a href="<?php echo $block->getUrl('bellnotification/') ?>">My Notification
			<?php echo ($block->getNotificationCounter()) ? '<span>(' . $block->escapeHtml($block->getNotificationCounter()) . ')</span>' : ''; ?>
		</a>
	</li>
<?php } ?>