<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Company\Block\Company\CompanyProfile $block
 * @var \Magento\Framework\DataObject $formSelectOptionsData
 */
$formMessages = $block->getFormMessages();
$countries = $block->getCountriesList();
$company = $block->getCustomerCompany();
?>

<?php if (!empty($formMessages)): ?>
    <div id="company_edit_form_messages">
        <?php foreach ($formMessages as $formMessage): ?>
            <div class="message error">
                <span><?= $block->escapeHtml($formMessage) ?></span>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<form class="form form-edit-company drl-cmpy-prfile" method="post" id="company-edit-form"
      action="<?= $block->escapeUrl($block->getUrl('*/profile/editPost')) ?>"
      data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <?php if ($block->isEditAccountAllowed()): ?>
    <fieldset class="fieldset info drl-cmpy-prifle-width">
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend>
        <div class="drl-register">
        <div class="field company-name _required drl-width-input">
            <label class="label" for="company_name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company_name" id="company_name"
                       value="<?= $block->escapeHtmlAttr($company->getCompanyName()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>"
                       class="drl-register-input input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field legal-name drl-width-input">
            <label class="label" for="legal_name">
                <span><?= $block->escapeHtml(__('Company Legal Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="legal_name" id="legal_name"
                       value="<?= $block->escapeHtmlAttr($company->getLegalName()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Company Legal Name')) ?>"
                       class="drl-register-input input-text">
            </div>
        </div>
    </div>
    <div class="drl-register">
        <div class="field company-email drl-width-input">
            <label class="label" for="company_email">
                <span><?= $block->escapeHtml(__('Company Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="company_email" id="company_email"
                       value="<?= $block->escapeHtmlAttr($company->getCompanyEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Company Email')) ?>"
                       data-role="email"
                       class="drl-register-input input-text" data-validate="{'validate-email':true}">
            </div>
        </div>
        <div class="field vat-tax-id drl-width-input">
            <label class="label" for="vat_tax_id">
                <span><?= $block->escapeHtml(__('VAT/TAX ID')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="vat_tax_id" id="vat_tax_id"
                       value="<?= $block->escapeHtmlAttr($company->getVatTaxId()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('VAT/TAX ID')) ?>"
                       class="drl-register-input input-text" placeholder="Enter VAT/TAX ID">
            </div>
        </div>
    </div>
    <div class="drl-register">
        <div class="field reseller-id drl-width-input-half">
            <label class="label" for="reseller_id">
                <span><?= $block->escapeHtml(__('Re-seller ID')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="reseller_id" id="reseller_id"
                       value="<?= $block->escapeHtmlAttr($company->getResellerId()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Re-seller ID')) ?>"
                       class="drl-register-input input-text" placeholder="Enter Re-seller IDf">
            </div>
        </div>
    </div>
    </fieldset>
    <?php endif; ?>
    <?php if ($block->isEditAddressAllowed()): ?>
    <fieldset class="fieldset info drl-cmpy-prifle-width">
        <legend class="legend"><span><?= $block->escapeHtml(__('Legal Address')) ?></span></legend>
        <?php $street = $company->getStreet(); ?>
          <div class="drl-register">
        <div class="field street _required drl-width-input">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Street Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="street[0]" id="street0"
                       value="<?= (!empty($street[0])) ? $block->escapeHtmlAttr($street[0]) : ''; ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       class="drl-register-input input-text" data-validate="{required:true}" placeholder="Enter Street Address"/>
            </div>
        </div>
        <div class="field street drl-width-input">
               <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Street Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="street[1]" id="street1"
                       value="<?= (!empty($street[1])) ? $block->escapeHtmlAttr($street[1]) : ''; ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       class="drl-register-input input-text" placeholder="Enter Street Address">
            </div>
        </div>
    </div>
      <div class="drl-register">
        <div class="field city _required drl-width-input">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="city" id="city"
                       value="<?= $block->escapeHtmlAttr($company->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="drl-register-input input-text" data-validate="{required:true}" placeholder="Enter City">
            </div>
        </div>
        <div class="field country_id _required drl-width-input">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $company->getCountryId(); ?>
                <select name="country_id" id="country_id"
                        title="<?= $block->escapeHtmlAttr(__('Country')) ?>"
                        data-validate="{required:true}" class="drl-register-input">
                    <option value=""></option>
                    <?php foreach ($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtmlAttr($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
      <div class="drl-register">
        <div class="field region-id required drl-width-input">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control _required">
                <select name="region_id" id="region_id" data-validate="{required:true}" class="drl-register-input">
                    <option value="">
                        <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                    </option>
                </select>
                <input type="text" id="region" name="region"
                       value="<?= $block->escapeHtmlAttr($company->getRegion()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                       class="input-text no-display">
            </div>
        </div>
        <div class="field postcode required drl-width-input">
            <label class="label" for="postcode">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="postcode" id="postcode"
                       value="<?= $block->escapeHtmlAttr($company->getPostcode()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('ZIP/Postal Code')) ?>"
                       class="drl-register-input input-text" placeholder="Enter ZIP/Postal Code">
            </div>
        </div>
    </div>
      <div class="drl-register">
        <div class="field telephone _required drl-width-input-half">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="telephone" id="telephone"
                       value="<?= $block->escapeHtmlAttr($company->getTelephone()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="drl-register-input input-text" data-validate="{required:true}" placeholder="Enter Telephone">
            </div>
        </div>
    </div>
    </fieldset>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>

<?php
$regionValue = ((int)$company->getRegionId()) ? (int)$company->getRegionId() : '';
/* @var Magento\Directory\Helper\Data $directoryDataHelper */
$directoryDataHelper = $block->getData('directoryDataHelper');
$regionJson = $directoryDataHelper->getRegionJson();
$countriesList = $directoryDataHelper->getCountriesWithOptionalZip(true);
?>
<script type="text/x-magento-init">
    {
        "#company-edit-form": {
            "validation": {}
        },
        "#country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": "true",
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#postcode",
                "form": "#company-edit-form",
                "regionJson": <?= /* @noEscape */ $regionJson ?>,
                "defaultRegion": "<?= /* @noEscape */ $regionValue ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $countriesList ?>
            }
        }
    }
</script>
