<div class="block block-collapsible-nav">
        <div class="title block-collapsible-nav-title"></div>
        <div class="content block-collapsible-nav-content" id="block-collapsible-nav">
            <ul class="nav items">
                <li class="nav item current-o"><a href="<?php echo $block->getBaseUrl() . 'servicerequest/index/index/'; ?>">Submit a Request</a></li>
                <li class="nav item current-t"><a href="<?php echo $block->getBaseUrl() . 'servicerequest/index/activerequest/'; ?>">Active Requests</a></li>
                <li class="nav item current-th"><a href="<?php echo $block->getBaseUrl() . 'servicerequest/index/requesthistory/'; ?>">Completed Requests</a></li>
            </ul>
        </div>
</div>
