<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$custom_helper = $this->helper('Ecomm\Theme\Helper\Output');
$_loggedin = $this->helper('Magento\Checkout\Helper\Cart')->getCart()->getCustomerSession()->isLoggedIn();
?>
<?php
$blockObj = $block->getLayout()->createBlock('Ecomm\HinEligibilityCheck\Block\exclusivePrice');
$priceLogicBlock = $block->getLayout()->createBlock('Ecomm\PriceEngine\Block\CustomPriceLogic');
$exclusivePriceMethod = $blockObj->getCollection();
$addressRepo = $blockObj->getAddressCollection();
$customerId = $priceLogicBlock->getCustomerId();
$customerGroupId = $priceLogicBlock->getCustomerGroupId();
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$application_verified_status = false;

if ($customerSession->isLoggedIn()) {

    $customerRepository = $objectManager->get('\Magento\Customer\Api\CustomerRepositoryInterface');
    $_eavConfig = $objectManager->get('\Magento\Eav\Model\Config');

    if ($customerSession->getId()) {

        $customerData = $customerRepository->getById($customerSession->getId());

        $attribute = $_eavConfig->getAttribute('customer', 'application_status');
        $options = $attribute->getSource()->getAllOptions();
        $application_statuses = [];
        foreach ($options as $option) {
            if ($option['value'] > 0) {
                $application_statuses[$option['value']] = $option['label'];
            }
        }
        $application_status = 0;
        $approved_id = array_search("Approved", $application_statuses);
        if ($customerData->getCustomAttribute('application_status')) {
            $application_status = $customerData->getCustomAttribute('application_status')->getValue();
        }

        if ($approved_id == $application_status) {
            $application_verified_status = true;
        }
    }
}
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
$type = 'widget-product-carousel';

$image = 'new_products_content_widget_grid';
$items = $block->getProductCollection()->getItems();

$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
    <ol class="product-items <?=/* @noEscape */$type?>">
        <?php $iterator = 1;?>
        <?php foreach ($items as $_item): ?>
            <?php $product_sku = $_item->getSku();?>

            <?php if ($customerSession->isLoggedIn()): ?>
                <?php
$customerInfo = $customerRepository->getById($customerId);

$shippingAddressId = $customerInfo->getDefaultShipping();
$addressInfo = $addressRepo->getById($shippingAddressId);
$hinStatus = '';
if ($addressInfo->getCustomAttribute('hin_status')) {
    $hinStatus = $addressInfo->getCustomAttribute('hin_status')->getValue();
}

?>
            <?php endif;?>
            <?=/* @noEscape */($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">'?>
            <div class="product-item-info">
                <?php if ($showWishlist || $showCompare): ?>
                    <?php if ($application_verified_status) {?>
                        <div class="actions-secondary" data-role="add-to-links">
                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                <a href="#"
                                data-post='<?=/* @noEscape */$block->getAddToWishlistParams($_item)?>' class="action towishlist" data-action="add-to-wishlist" title="<?=$block->escapeHtmlAttr(__('Add to Wish List'))?>">
                                    <span><?=$block->escapeHtml(__('Add to Wish List'))?></span>
                                </a>
                            <?php endif;?>
                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                <a href="#" class="action tocompare" data-post='<?=/* @noEscape */$compareHelper->getPostDataParams($_item)?>' title="<?=$block->escapeHtmlAttr(__('Add to Compare'))?>">
                                    <span><?=$block->escapeHtml(__('Add to Compare'))?></span>
                                </a>
                            <?php endif;?>
                        </div>
                    <?php }?>
                <?php endif;?>
                <a href="<?=$block->escapeUrl($block->getProductUrl($_item))?>" class="product-item-photo">
                    <?=$block->getImage($_item, $image)->toHtml()?>
                </a>
                <?php
$_productNameLength = strlen($block->escapeHtml($_item->getName()));

if ($_productNameLength < 57) {
    $_productName = $block->escapeHtml($_item->getName());
} else {
    $_productName = substr($block->escapeHtml($_item->getName()), 0, 55) . '...';
}
?>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a title="<?=$block->escapeHtml($_item->getName())?>"
                           href="<?=$block->escapeUrl($block->getProductUrl($_item))?>"
                           class="product-item-link">
                            <?=$_productName?>
                        </a>
                    </strong>
                    <div class="drl-sku-cashback-attribute"><?=$block->escapeHtml(__('NDC #:'))?> <span class="drl-sku-product product-attribute-sku-<?php echo $_item->getId(); ?>"><?=/* @noEscape */$_helper->productAttribute($_item, $_item->getSku(), 'sku')?></span>
                        </div>
                        <br>
                    <?php if ($application_verified_status) {?>
                        <?php if ($_item->getTypeId() == 'simple') {
    $salable_quantities = $StockState->execute($_item->getSku());
}?>
                        <div class="drl-sku-cashback-attribute-second">
                            <!--<span class="product-available-stock drl-cashback-stock">
                                Packs Available: <span id="product-available-qty-value-<?php echo $_item->getSku(); ?>">
                                <?php /*if($_item->getTypeId() == 'simple') {
$salable_quantities = $StockState->execute($_item->getSku());
echo $salable_quantities[0]['qty'];
} */?></span>
                            </span>-->
                            <?php
if ($_item->getTypeId() == 'simple') {
    $salable_quantities = $StockState->execute($_item->getSku());
}

    $stockstatus = $custom_helper->getConfigVal('cataloginventory/options/display_product_stock_status');
    if ($stockstatus) {
        if ($_item->getTypeId() == 'simple') {
            /*Getting the config Out Of Stock Threshold value*/
            $config_min_qty = $custom_helper->getDefaultOutOfStockVal();

            $_productStock = $custom_helper->getStockItem($_item->getId());

            /*Checking the whether instock or out of stock*/
            $instock = 1;

            if (!isset($salable_quantities[0]) || $salable_quantities[0]['qty'] <= $config_min_qty) {
                $instock = 0;
            }

            ?>
                                    <?php if ($instock && $_productStock->getQty() > 0) {?>
                                        <div class="stock stock-available">
                                            <span><?=$escaper->escapeHtml(__('In stock'))?></span>
                                        </div>
                                    <?php } else {?>
                                        <div class="stock stock-unavailable">
                                            <span><?=$escaper->escapeHtml(__('Out of stock'))?></span>
                                        </div>
                                    <?php }?>
                                <?php }
    }?>
                        </div>
                    <?php }?>
                        <?php if ($_helper->productAttribute($_item, $_item->getStrength(), 'strength')) {?>
                            <div class="drl-sku-cashback-attribute-second">
                                <div class="attribute-pack-size">
                                    <div class="swatch-attribute pack_sizes" >
                                        <span class="swatch-attribute-label">Total Content: </span>
                                        <span class="swatch-attribute-value"><?php echo $_item->getResource()->getAttribute('strength')->setStoreId(0)->getFrontend()->getValue($_item); ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php }?>
                        <?php if ($_helper->productAttribute($_item, $_item->getPackSize(), 'pack_size')) {?>
                            <div class="drl-sku-cashback-attribute-second">
                                <span class="swatch-attribute-label">Pack Size</span>
                                <div class="drl-swatch-attribute-options">
                                <div class="drl-attribute-strength">
                                    <?php echo $_item->getResource()->getAttribute('pack_size')->setStoreId(0)->getFrontend()->getValue($_item); ?>
                                </div>
                            </div>
                            </div>
                        <?php }?>
                    <?php if ($templateType): ?>
                        <?=$block->getReviewsSummaryHtml($_item, $templateType)?>
                    <?php endif;?>

                    <?=$block->getProductDetailsHtml($_item)?>
                    <?php $price = array();?>
                   <?php $finalPrice = array();?>
                    <?php if ($customerSession->isLoggedIn()) {?>
                       <?php $regularprice = $priceLogicBlock->getCustomRegularPrice($customerId, $_item);
                        $price[] = $regularprice['price'];
                        ?>

                        <?php if ($hinStatus == "1") {
        $subWac = $priceLogicBlock->get340bPrice('sub_wac', $_item);

        // $subWac = $_product->getResource()->getAttribute('sub_wac')->setStoreId(0)->getFrontend()->getValue($_product);
        if (isset($subWac['price'])) {
            $price[] = $subWac['price'];
        }
        $phsIndirect = $priceLogicBlock->get340bPrice('phs_indirect', $_item);

        // $phsIndirect = $_product->getResource()->getAttribute('phs_indirect')->setStoreId(0)->getFrontend()->getValue($_product);

        if (isset($phsIndirect['price'])) {
            $price[] = $phsIndirect['price'];
        }
        // sort($price);

        foreach ($price as $prices) {
            if ($prices == 0) {
                continue;
            } else {
                $finalPrice[] = $prices;
            }
        }

    } else {
        foreach ($price as $prices) {
            if ($prices == 0) {
                continue;
            } else {
                $finalPrice[] = $prices;
            }
        }
    }
    ?>
                        <?php }?>
                    <?php if ($customerSession->isLoggedIn()) {?>

                        <?php if (isset($finalPrice) && $finalPrice != null) {?>
                    <p class="fea-price"><span class="fea-min-price"><?='$' . number_format(min($finalPrice), 2);?></span> - <span class="fea-max-price"><?='$' . number_format(max($finalPrice), 2);?></span></p>
                    <p class="fea-view-para" ><a href="<?=$block->escapeUrl($block->getProductUrl($_item))?>" class="fea-view-dtl">View Details</a></p>
                    <?php } else {?>
                        <p class="fea-view-para" ><a href="<?=$block->escapeUrl($block->getProductUrl($_item))?>" class="fea-view-dtl">View Details</a></p>
                            <?php }?>
                    <?php }?>
                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                        <div class="product-item-inner">
                            <div class="product-item-actions">
                                <?php if ($showCart): ?>
                                    <?php if (($application_verified_status) && (isset($salable_quantities[0]) && $salable_quantities[0]['qty'] > 0)) {?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item);?>
                                                <?php if ($_item->getPriceInfo()->getPrice('final_price')->getValue() != 0) {?>
                                                    <form data-role="tocart-form" data-product-sku="<?=$block->escapeHtml($_item->getSku())?>" action="<?=$block->escapeUrl($postParams['action'])?>" method="post">
                                                        <input type="hidden" name="product" value="<?=$block->escapeHtmlAttr($postParams['data']['product'])?>">
                                                        <input type="hidden" name="<?=/* @noEscape */Action::PARAM_NAME_URL_ENCODED?>" value="<?=/* @noEscape */$postParams['data'][Action::PARAM_NAME_URL_ENCODED]?>">
                                                        <?=$block->getBlockHtml('formkey')?>
                                                    </form>
                                                <?php }?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?=$block->escapeHtml(__('In stock'))?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?=$block->escapeHtml(__('Out of stock'))?></span></div>
                                                <?php endif;?>
                                            <?php endif;?>
                                        </div>
                                    <?php }?>
                                <?php endif;?>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            </div>
            <?=($iterator == count($items) + 1) ? '</li>' : ''?>
        <?php endforeach?>
    </ol>
<?php endif;?>