<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
  <div class="drl-badge"><span class="drl-need-mod-white">Need modification? <a class="drl-need-mod-hyp-white" href="<?php echo $this->getBaseUrl()."help-support";?>"> Click here</a></span></div>
<form class="form form-edit-account account-drl-heading"
      action="<?= $block->escapeUrl($block->getUrl('customer/business/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info drl-info-account">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend drl-page-title"><span><?= $block->escapeHtml(__('Business Identification')) ?></span></legend><br>
        <div class="drl-register">
           <div class="field field-business_type drl-width-input">
              <label class="label" for="business_type"><span>Type of Business </span></label>
              <div class="control">
                 <?php
                 $business_type = '';
                  if (!empty($block->getCustomer()->getCustomAttribute("business_type"))) {
                        $business_type =  $block->getCustomer()->getCustomAttribute("business_type")->getValue();
                  }
                  ?>
                 <select id="business_type" name="business_type" class="drl-register-input" disabled>
                    <option value="" >Select a Business</option>
                    <?php foreach($block->getBusinessTypes() as $business_type_data) { ?>tests
                      <option value="<?php echo $business_type_data['value']; ?>" <?php if($business_type == $business_type_data['value']){ ?> selected="selected"<?php } ?>><?php echo $business_type_data['label']; ?></option>
                    <?php } ?>
                 </select>
              </div>
           </div>
           <div class="field field-business_other drl-width-input">
              <label class="label" for="business_other"><span>If Type of Business is “Other”, Please Provide Information </span></label>
              <div class="control">
                 <input type="text" id="business_other" name="business_other" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("business_other"))) { echo $block->getCustomer()->getCustomAttribute("business_other")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Information" disabled>
              </div>
           </div>
        </div>

        <div class="drl-hr-line"></div>
        <?php
        $edi_capabilities = 0;
        if (!empty($block->getCustomer()->getCustomAttribute("fill_edi_capabilities"))) {
          $edi_capabilities = $block->getCustomer()->getCustomAttribute("fill_edi_capabilities")->getValue();
        }
        ?>
        <div class="field field-edi_capabilities required">
           <label class="label drl-required-astr" for="edi_capabilities"><span>Does Your Company Have EDI Capabilities</span></label>
           <div class="control drl-checkbox-y-n">
              <input class="checkbox-tools" type="radio" name="tools" id="tool-1" <?php if($edi_capabilities == 1) { ?>checked="checked"<?php } ?> disabled>
              <label class="for-checkbox-tools" for="tool-1">
              Yes
              </label>
              <input class="checkbox-tools" type="radio" name="tools" id="tool-2"<?php if($edi_capabilities == 0) { ?>checked="checked"<?php } ?> disabled>
              <label class="for-checkbox-tools" for="tool-2">
              No
              </label>
           </div>
        </div>
        <div class="drl-register">
           <div class="field field-gln_no drl-width-input">
              <label class="label" for="gln_no"><span>Please fill the EDI Capabilities</span></label>
              <div class="control">
                <textarea placeholder="Enter EDI Capabilities" class="drl-register-input input-text" id="fill_edi_capabilities drl-register-input" name="fill_edi_capabilities" disabled><?php if (!empty($block->getCustomer()->getCustomAttribute("fill_edi_capabilities"))) { echo $block->getCustomer()->getCustomAttribute("fill_edi_capabilities")->getValue(); } ?></textarea>
              </div>
           </div>
        </div>
        <div class="drl-hr-line"></div>
        <div class="drl-register">
            <div class="field field-idn_affiliation drl-width-input">
              <label class="label" for="idn_affiliation"><span>IDN Affiliation</span></label>
              <div class="control">
                 <input type="text" id="idn_affiliation" name="idn_affiliation" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("idn_affiliation"))) { echo $block->getCustomer()->getCustomAttribute("idn_affiliation")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter IDN Affiliation" disabled>
              </div>
           </div>
           <div class="field field-gln_no drl-width-input">
           </div>

        </div>
        <div class="drl-register">
            <div class="field field-partof_organization drl-width-input required">
              <label class="label drl-required-astr" for="partof_organization"><span>If Part of a GPO, Please Select GPO Name </span></label>
              <div class="control">
                <?php
                    $partof_organization = '';
                    if (!empty($block->getCustomer()->getCustomAttribute("partof_organization"))) {
                        $partof_organization =  $block->getCustomer()->getCustomAttribute("partof_organization")->getValue();
                    }
                ?>
                 <select id="partof_organization" name="partof_organization" class="drl-register-input input-text required" disabled>
                    <option value="">Select GPO</option>
                    <?php foreach($block->getGpoList() as $gpo_list) { ?>tests
                      <option value="<?php echo $gpo_list['value']; ?>" <?php if($partof_organization == $gpo_list['value']){ ?> selected="selected"<?php } ?>><?php echo $gpo_list['label']; ?></option>
                    <?php } ?>
                 </select>
              </div>
           </div>
           <div class="field field-gpo_others drl-width-input">
              <label class="label" for="gpo_others"><span>Other GPO Name</span></label>
              <div class="control">
                 <input type="text" id="gpo_others" name="gpo_others" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("gpo_others"))) { echo $block->getCustomer()->getCustomAttribute("gpo_others")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Other GPO Name" disabled>
              </div>
           </div>
        </div>
        <div class="drl-register">
            <div class="field field-partof_organization drl-width-input">
              <label class="label drl-required-astr" for="disproportionate_hospital"><span>Are you disproportionate hospital?</span></label>
               <div class="control">
                <?php
                    $disproportionate_hospital = '';
                    if (!empty($block->getCustomer()->getCustomAttribute("disproportionate_hospital"))) {
                        $disproportionate_hospital =  $block->getCustomer()->getCustomAttribute("disproportionate_hospital")->getValue();
                    }
                ?>
                  <select id="disproportionate_hospital" name="disproportionate_hospital" class="drl-register-input input-text required" disabled>
                     <option value="" selected="selected"></option>
                     <option value="0"<?php if($disproportionate_hospital == 0){ ?> selected="selected"<?php } ?>>No</option>
                     <option value="1"<?php if($disproportionate_hospital == 1){ ?> selected="selected"<?php } ?>>Yes</option>
                  </select>
               </div>
           </div>
           <div class="field field-monthly_purchase drl-width-input">
              <label class="label" for="monthly_purchase"><span>Expected Monthly Purchases </span></label>
              <div class="control">
                 <input type="text" id="monthly_purchase" name="monthly_purchase" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("monthly_purchase"))) { echo $block->getCustomer()->getCustomAttribute("monthly_purchase")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Expected Monthly Purchases" disabled>
              </div>
           </div>
        </div>
        <div class="drl-hr-line"></div>
    </fieldset>

    <?= $block->getChildHtml('form_additional_info') ?>
<!--     <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div> -->
</form>
<script>
   require([
       'jquery',
       'mage/url',
       'Magento_Ui/js/modal/modal',
       'drlnumberjs'
   ], function($, url, modal) {
        $(document).ready(function(){

            $('#trade_as_corporate').change(function(){
                if (this.checked) {
                    $('#trade_as_corporate').val(1);
                    $('#trade-add-form').hide('slow');
                } else {
                    $('#trade_as_corporate').val(0);
                    $('#trade-add-form').show('slow');
                }
            });
        });

     $(document).ready(function(){
        $(".drl-with-coun").intlTelInput({
          initialDialCode: true,
          americaMode: false,
          onlyCountries: ["us"]

        });
      });
    });
</script>