<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<form class="form form-edit-account drl-frgt-chng-pawd"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>
        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <!-- <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label drl-change" for="change-email">
                <span><?= $block->escapeHtml(__('Change Email')) ?></span>
            </label>
        </div> -->
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label drl-change" for="change-password">
                <span><?= $block->escapeHtml(__('Change Password')) ?></span>
            </label>
        </div>
    </fieldset>

    <fieldset class="fieldset password drl-change-email-password" data-container="change-email-password">
        <legend class="legend">
            <span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span>
        </legend><br>
        <div class="field email required drl-change-he" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="drl-register-input input-text"
                       data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required drl-change-he">
            <label class="label" for="current-password">
                <span><?= $block->escapeHtml(__('Current Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="drl-register-input input-text" name="current_password" id="current-password"
                       data-input="current-password"
                       autocomplete="off" placeholder="Enter Current Password" />
            </div>
        </div>
        <div class="field new password required drl-change-he" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <?php $minCharacterSets = $block->getRequiredCharacterClassesNumber() ?>
                <input type="password" class="drl-register-input input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($minCharacterSets) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" placeholder="Enter New Password"/>
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation password required drl-change-he" data-container="confirm-password">
            <label class="label" for="password-confirmation">
                <span><?= $block->escapeHtml(__('Confirm New Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="drl-register-input input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" placeholder="Enter Confirm Password" />
            </div>
        </div>
    </fieldset>

    <?= $block->getChildHtml('form_additional_info') ?>
    <div class="actions-toolbar">
        <div class="primary drl-right">
            <button type="submit" class="action save primary drl-btn-frgt-paswd" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<div class="columns drl-coulmns-width">
  <div class="drl-badge"><span class="drl-need-mod-white">Need modification? <a class="drl-need-mod-hyp-white" href="<?php echo $this->getBaseUrl()."help-support";?>"> Click here</a></span></div>
    <fieldset class="fieldset genral-info">
        <legend class="legend"><span><?= $block->escapeHtml(__('General Information')) ?></span></legend><br>
        <div class="drl-register">
           <div class="field field-legal_business_name drl-width-input">
              <label class="label drl-required-astr" for="legal_business_name"><span>Legal Business Name</span></label>
              <div class="control">
                 <input type="text" id="legal_business_name" name="legal_business_name" autocomplete="off" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("legal_business_name"))) { echo $block->getCustomer()->getCustomAttribute("legal_business_name")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Enter Legal Business Name" disabled>
              </div>
           </div>
           <div class="field field-dba drl-width-input">
              <label class="label" for="dba"><span>DBA</span></label>
              <div class="control">
                <input type="text" id="dba" name="dba" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("dba"))) { echo $block->getCustomer()->getCustomAttribute("dba")->getValue(); } ?>" class="drl-register-input input-text " placeholder="Enter DBA" disabled>
              </div>
           </div>
        </div>
        <div class="drl-register">
           <div class="field field-duns_number drl-width-input">
              <label class="label" for="duns_number"><span>D-U-N-S Number </span></label>
              <div class="control ">
                 <input type="text" id="duns_number" name="duns_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("duns_number"))) { echo $block->getCustomer()->getCustomAttribute("duns_number")->getValue(); } ?>" class="drl-register-input input-text validate-digits" placeholder="35 - 345 - 6545" required disabled>
                 <!--drl-flex drl-register-input-word <label class="drl-input-side-word">Verify</label>-->
              </div>
           </div>
           <div class="field field-company_website drl-width-input">
              <label class="label" for="company_website"><span>Company Website </span></label>
              <div class="control">
                 <input type="text" id="company_website" name="company_website" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_website"))) { echo $block->getCustomer()->getCustomAttribute("company_website")->getValue(); } ?>" class="drl-register-input input-text validate-url" placeholder="Enter Company Website" disabled>
              </div>
           </div>
         </div>
           <div class="drl-hr-line"></div>
           <div class="drl-register">
               <div class="field field-contact_person drl-width-input-half">
                  <label class="label" for="contact_person"><span>Person you have been in contact with at Dr. Reddy's? </span></label>
                  <div class="control">
                     <input type="text" id="contact_person" name="contact_person" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("contact_person"))) { echo $block->getCustomer()->getCustomAttribute("contact_person")->getValue(); } ?>" class="drl-register-input input-text" placeholder="Enter Name" disabled>
                  </div>
               </div>
            </div>
        <div class="drl-hr-line"></div>
    </fieldset>
  </div>
<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = {$ignore};

        dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
        });

    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $changeEmailAndPasswordTitle = $block->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
