<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>

<div class="block block-customer-login-container">

    <div class="cus-title">
       <strong class="cus-login-title">   <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/Logo-reg-for-d.png'); ?>' alt="customer-icon" width="150" height="33"> </strong>
   </div>

   <div class="cus-title-below">
      <span class="cus-login-title-below"> Welcome to <span class="cus-log-tlt-sec"> Dr.Reddy’s Direct! </span> </span>
   </div>
 
 <?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('news_scroll')
->toHtml();
?>

</div>

<div class="block block-customer-forgot-containter">

<div class="block-customer-forgot-inner">


<form class="form password forget forgot-pass-inner"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
       <!-- <div class="field note"><?= $block->escapeHtml(__('Enter the company email ID associated with Your account')) ?></div> -->
       <div class="forgot-company-title"><a class="action forgot-back back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('')) ?></span></a> Set a Password</div>

        <div class="forgot-company--below-title">Enter the company email ID associated with Your account</div>

        <div class="forgot-red-msg">We will send the reset link</div>


        <div class="field email customer-login-email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Company Email ID')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text customer-login-input" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="Abcd@companyname.com">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>  
    </fieldset>

    <div class="actions-toolbar">
        <div class="customer-login-button">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Send reset link')) ?></span></button>
        </div>       
    </div>

    <div class="actions-toolbar">
         <div class="customer-dont-account"><span class="customer-d-acc">Don't have an account ?</span><span class="customer-d-signup"><a href="<?php echo $block->getUrl('register-landing-page'); ?>">Sign UP</a></span></div>                    
    </div>

</form>

</div>

    <div class="block-content-under">         

        <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/login-bottom.png'); ?>' alt="image-icon" width="30" height="25">

    </div>


</div>