<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>

<div class="cus-reset-password">

<div class="cus-reset-image">
       <strong class="cus-login-image">   <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/customer-login-logo-updated.png'); ?>' alt="customer-icon" > </strong>
</div>

<div class="cus-pass-reset">
   <span class="cus-pass-head">  Password Reset  </span>
</div>

<div class="cus-pass-head-below">
   <span class="cus-pass-new">Enter the new password for xxxxwar@abc.com</span>
</div>

<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
      method="post"
        <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password customer-pass-reset reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field password cus-new-pass required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                
              <!--  <input type="password" class="input-text confirm-pass-cus-input" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}" 
                       autocomplete="off"> -->

                <input type="password" name="password" id="password"
                             title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                             class=" confirm-pass-cus-input input-text passwordstrength"
                             data-password-min-length="<?=
                              $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                             data-password-min-character-sets="<?=
                              $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                             data-validate="{required:true, 'validate-customer-password':true}"
                             autocomplete="off" placeholder="Enter Password">

             <!--   <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div> -->
            </div>

           <div class="pass-must">

               <div class="pass-must-head">
                  Password must contain minimum of
               </div>

               <div class="pass-must-list">

                  <div id="message-drl">
                         <div class="drl-flex">
                            <p id="letter" class="invalid msg-width-drl">One Lower Case</p>
                            <p id="capital" class="invalid msg-width-drl">One Upper Case</p>
                         </div>
                         <div class="drl-flex">
                            <p id="number" class="invalid msg-width-drl">One Numeric</p>
                            <p id="regularExpression" class="invalid msg-width-drl">One Special Character</p>
                         </div>
                         <p id="length" class="invalid msg-width-drl1">8 Characters and Maximum of 16 Characters</p>
                    </div>

                </div>

            </div>

        </div>
        <div class="field confirmation confirm-pass-title required">
            <label class="label " for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text confirm-pass-cus-input" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off" placeholder="Abcd@companyname.com">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="confirm-pass-btn">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>


<div class="block-content-under">         

        <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/login-bottom.png'); ?>' alt="image-icon" width="30" height="25">

</div>



</div>

<script type="text/javascript">
   require(['resetpassjs'], function () {
   });
</script>