<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
  <div class="drl-badge"><span class="drl-need-mod-white">Need modification? <a class="drl-need-mod-hyp-white" href="<?php echo $this->getBaseUrl()."help-support";?>"> Click here</a></span></div>
<form class="form form-edit-account account-drl-heading"
      action="<?= $block->escapeUrl($block->getUrl('customer/trade/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info drl-info-account">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend drl-page-title"><span><?= $block->escapeHtml(__('Trade Information')) ?></span></legend><br>
        <div class="drl-register">
           <div class="field field-trade_businessname drl-width-input">
              <label class="label" for="trade_businessname"><span>Trade Reference Business Name</span></label>
              <div class="control">
                 <input type="text" id="trade_businessname" name="trade_businessname" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_businessname"))) { echo $block->getCustomer()->getCustomAttribute("trade_businessname")->getValue(); } ?>" class="drl-register-input input-text" placeholder="Enter Trade Reference Business Name" disabled>
              </div>
           </div>
           <div class="field field-trade_phone drl-width-input">
              <label class="label" for="trade_phone"><span>Phone Number </span></label>
              <div class="control">
                 <input type="text" id="trade_phone" name="trade_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_phone"))) { echo $block->getCustomer()->getCustomAttribute("trade_phone")->getValue(); } ?>" class="drl-with-coun drl-register-input-number input-text validate-digits" minlength="10" maxlength="10" placeholder="345 - 345 - 6545" disabled>
              </div>
           </div>
        </div>
        <div class="drl-register">
           <div class="field field-trade_email drl-width-input-half">
              <label class="label" for="trade_email"><span>E-mail Address</span></label>
              <div class="control">
                 <input type="text" id="trade_email" name="trade_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_email"))) { echo $block->getCustomer()->getCustomAttribute("trade_email")->getValue(); } ?>" class="drl-register-input input-text validate-email" placeholder="Enter Email ID" disabled>
              </div>
           </div>
        </div>
        <div class="drl-hr-line"></div>
        <div class="drl-billing-add-form">
           <div class="drl-bill-head">
              <legend class="drl-legends-second"><span class="drl-main-middle-head">
                 <?= $block->escapeHtml(__('Trade Address')) ?></span>
              </legend>
           </div>
           <div class="drl-switch-add-bill">
              <div >
                 <span class="drl-legends-third drl-title-middle-toogle"> Same as Corporate Address</span>
              </div>
              <div class="drl-switch-field">
                 <label class="switch">
                 <input class="toogle-check" name="trade_as_corporate" id="trade_as_corporate" type="checkbox" checked />
                 <span class="slider round"></span>
                 </label>
              </div>
           </div>
        </div>
         
        <div id="trade-add-form" style="display: none;">
           <div class="drl-register">
              <div class="field field-trade_address drl-width-input">
                 <label class="label drl-required-astr" for="trade_address"><span>Street Address </span></label>
                 <div class="control">
                    <input type="text" id="trade_address" name="trade_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_address"))) { echo $block->getCustomer()->getCustomAttribute("trade_address")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Primary Street Address" disabled>
                 </div>
              </div>
              <div class="field field-trade_city drl-width-input">
                 <label class="label drl-required-astr" for="trade_city"><span>City</span></label>
                 <div class="control">
                    <input type="text" id="trade_city" name="trade_city" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_city"))) { echo $block->getCustomer()->getCustomAttribute("trade_city")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter City" disabled>
                 </div>
              </div>
           </div>
           <div class="drl-register">
              <div class="field field-trade_state drl-width-input">
                 <label class="label drl-required-astr" for="trade_state"><span>State/Province </span></label>
                  <div class="control">
                    <?php if (!empty($block->getCustomer()->getCustomAttribute("trade_state"))) {
                        $selected_company_region = $block->getCustomer()->getCustomAttribute("trade_state")->getValue(); 
                    } else {
                        $selected_company_region = 0;
                    } ?>
                     <select id="trade_state" name="trade_state" class="drl-register-input input-text required" disabled>
                        <option value="">Please select a region, state or province.</option>
                        <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                            <?php if($idx > 0) { ?>
                                <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                            <?php } ?>
                        <?php } ?>
                     </select>
                  </div>
              </div>
               <div class="field field-trade_country drl-width-input">
                  <label class="label drl-required-astr" for="trade_country"><span>Country</span></label>
                  <div class="control">
                     <select id="trade_country" name="trade_country" class="drl-register-input input-text required" disabled>
                         <option value="US" selected="">United States</option>
                     </select>
                  </div>
               </div>
           </div>
           <div class="drl-register">
              <div class="field field-trade_zip drl-width-input">
                 <label class="label drl-required-astr" for="trade_zip"><span>Zip / Postal Code </span></label>
                 <div class="control">
                    <input type="text" id="trade_zip" name="trade_zip" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_zip"))) { echo $block->getCustomer()->getCustomAttribute("trade_zip")->getValue(); } ?>" class="input-text drl-register-input validate-zip-us required" placeholder="Enter Zip / Postal Code" disabled>
                 </div>
              </div>
                   <div class="field field-trade_fax drl-width-input">
                 <label class="label" for="trade_fax"><span>Fax Number</span></label>
                 <div class="control">
                    <input type="text" id="trade_fax" name="trade_fax" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_fax"))) { echo $block->getCustomer()->getCustomAttribute("trade_fax")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Zip / Postal Code" disabled>
                 </div>
              </div>
              
           </div>

        </div>
        <div class="drl-hr-line"></div>
    </fieldset>

    <?= $block->getChildHtml('form_additional_info') ?>
<!--     <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div> -->
</form>
<script>
   require([
       'jquery',
       'mage/url',
       'Magento_Ui/js/modal/modal',
       'drlnumberjs'
   ], function($, url, modal) {
        $(document).ready(function(){

            $('#trade_as_corporate').change(function(){
                if (this.checked) {
                    $('#trade_as_corporate').val(1);
                    $('#trade-add-form').hide('slow');
                } else {
                    $('#trade_as_corporate').val(0);
                    $('#trade-add-form').show('slow');
                }
            });
        });

     $(document).ready(function(){
        $(".drl-with-coun").intlTelInput({
          initialDialCode: true,
          americaMode: false,
          onlyCountries: ["us"]

        });
      });
    });
</script>