<?php
   /**
    * Copyright © Magento, Inc. All rights reserved.
    * See COPYING.txt for license details.
    */

   use Magento\Customer\Block\Widget\Name;

   /** @var \Magento\Customer\Block\Form\Edit $block */
   /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
   ?>
<div class="drl-page-title-wrapper">
   <h1 class="drl-page-title">
      <span class="base">Complete Profile</span>
   </h1>
   <h3 class="drl-page-sub-title"><span class="base">Complete your profile to access a wide range of products</span></h3>
</div>
<div class="drl-step-form">
   <form class="form form-edit-account sw sw-justified sw-theme-dots form-step-drl" action="<?= $block->escapeUrl($block->getUrl('customer/account/updatePost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
      <h3>
         <?= $block->escapeHtml(__('General Info')) ?>
      </h3>
      <fieldset class="fieldset info drl-general-info">
         <div id="ajax-field-0">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="steps_status" value="1" />
            <legend class="drl-legend"><span>
               <?= $block->escapeHtml(__('General Information')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field field-legal_business_name drl-width-input">
                  <label class="label drl-required-astr" for="legal_business_name"><span>Legal Business Name</span></label>
                  <div class="control">
                     <input type="text" id="legal_business_name" name="legal_business_name" autocomplete="off" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("legal_business_name"))) { echo $block->getCustomer()->getCustomAttribute("legal_business_name")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Enter Legal Business Name">
                  </div>
               </div>
               <div class="field field-dba drl-width-input">
                  <label class="label" for="dba"><span>DBA</span></label>
                  <div class="control">
                    <input type="text" id="dba" name="dba" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("dba"))) { echo $block->getCustomer()->getCustomAttribute("dba")->getValue(); } ?>" class="drl-register-input input-text " placeholder="Enter DBA">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-duns_number drl-width-input">
                  <label class="label drl-required-astr" for="duns_number"><span>D-U-N-S Number </span></label>
                  <div class="control ">
                     <input type="text" id="duns_number" name="duns_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("duns_number"))) { echo $block->getCustomer()->getCustomAttribute("duns_number")->getValue(); } ?>" class="drl-register-input input-text validate-digits required" placeholder="35 - 345 - 6545" required>
                     <!--drl-flex drl-register-input-word <label class="drl-input-side-word">Verify</label>-->
                  </div>
               </div>
               <div class="field field-company_website drl-width-input">
                  <label class="label" for="company_website"><span>Company Website </span></label>
                  <div class="control">
                     <input type="text" id="company_website" name="company_website" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_website"))) { echo $block->getCustomer()->getCustomAttribute("company_website")->getValue(); } ?>" class="drl-register-input input-text validate-url" placeholder="Enter Company Website - https://www.example.com">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <legend class="drl-legends-second"><span>
               <?= $block->escapeHtml(__('Corporate Address')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field field-corporate_street drl-width-input">
                  <label class="label drl-required-astr" for="corporate_street"><span>Primary Street (No P. O. Boxes)</span></label>
                  <div class="control">
                     <input type="text" id="company_street" name="company_street" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_street"))) { echo $block->getCustomer()->getCustomAttribute("company_street")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Primary Street (No P. O. Boxes)">
                  </div>
               </div>
               <div class="field field-corporate_city drl-width-input">
                  <label class="label drl-required-astr" for="corporate_city"><span>City</span></label>
                  <div class="control">
                    <input type="text" id="company_city" name="company_city" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_city"))) { echo $block->getCustomer()->getCustomAttribute("company_city")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Enter City">
                  </div>
               </div>
            </div>

            <div class="drl-register">
               <div class="field field-corporate_state drl-width-input">
                  <label class="label drl-required-astr" for="corporate_state"><span>State</span></label>
                  <div class="control">
                    <?php if (!empty($block->getCustomer()->getCustomAttribute("company_state"))) {
                        $selected_company_region = $block->getCustomer()->getCustomAttribute("company_state")->getValue(); 
                    } else {
                        $selected_company_region = 0;
                    } ?>
                     <select id="company_state" name="company_state" class="drl-register-input input-text required">
                        <option value="" selected data-default>Please select a region, state or province.</option>
                        <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                            <?php if($idx > 0) { ?>
                                <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                            <?php } ?>
                        <?php } ?>
                     </select>
                  </div>
               </div>
               <div class="field field-corporate_country drl-width-input">
                  <label class="label drl-required-astr" for="corporate_country"><span>Country</span></label>
                  <div class="control">
                     <select id="company_country" name="company_country" class="drl-register-input input-text required">
                         <option value="US" selected="">United States</option>
                     </select>
                  </div>
               </div>
            </div>

            <div class="drl-register">
               <div class="field field-corporate_zip drl-width-input">
                  <label class="label drl-required-astr" for="corporate_zip"><span>ZIP/Postal Code</span></label>
                  <div class="control">
                     <input type="text" id="company_zip" name="company_zip" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_zip"))) { echo $block->getCustomer()->getCustomAttribute("company_zip")->getValue(); } ?>" minlength="5" maxlength="5" class="drl-register-input input-text required validate-digits validate-zip-us required" placeholder="Enter ZIP/Postal Code">
                  </div>
               </div>
               <div class="field field-corporate_telephone drl-width-input">
                  <label class="label drl-required-astr" for="corporate_telephone"><span>Phone Number</span></label>
                  <div class="control">
                     <input type="text" id="company_phone" name="company_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("company_phone"))) { echo $block->getCustomer()->getCustomAttribute("company_phone")->getValue(); } ?>" minlength="10" maxlength="10" class="drl-with-coun drl-register-input-number input-text required validate-digits" placeholder="Enter Phone Number">
                  </div>
               </div>
            </div>

            <div class="drl-register">
               <div class="field field-corporate_fax drl-width-input-half">
                  <label class="label" for="corporate_fax"><span>FAX Number</span></label>
                  <div class="control">
                     <input type="text" id="fax_number" name="fax_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("fax_number"))) { echo $block->getCustomer()->getCustomAttribute("fax_number")->getValue(); } ?>" class="drl-register-input input-text validate-digits" placeholder="Enter FAX Number">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-billing-add-form">
               <div class="drl-bill-head">
                  <legend class="drl-legends-second"><span class="drl-main-middle-head">
                     <?= $block->escapeHtml(__('Billing Address')) ?></span>
                  </legend>
               </div>
               <div class="drl-switch-add-bill">
                  <div >
                     <span class="drl-legends-third drl-title-middle-toogle"> Same as Corporate Address</span>
                  </div>
                  <div class="drl-switch-field">
                    <?php
                        $billing_address = [];
                        $billing_as_corporate = 1;
                        if (!empty($block->getCustomer()->getCustomAttribute("billing_as_corporate"))) {
                            $billing_as_corporate = $block->getCustomer()->getCustomAttribute("billing_as_corporate")->getValue();
                        }

                        if($billing_as_corporate == 0){
                          $billing_address = $block->getBillingAddress();
                        }
                        //$billing_address = $block->getBillingAddress();
                    ?>
                    <label class="switch">
                        <input class="toogle-check" name="billing_as_corporate" id="billing_as_corporate" type="checkbox" value="<?php echo $billing_as_corporate; ?>" <?php if($billing_as_corporate == 1){ ?>checked <?php } ?>/>
                        <span class="slider round"></span>
                    </label>
                  </div>
               </div>
            </div>
            <div id="billing-address-block" <?php if($billing_as_corporate == 1){ ?>style="display: none;" <?php } ?>>
           <br>
                <div class="drl-register">
                   <div class="field field-billing_street drl-width-input">
                      <label class="label drl-required-astr" for="billing_street"><span>Primary Street (No P. O. Boxes)</span></label>
                      <div class="control">
                         <input type="text" id="billing_street" name="billing[street]" value="<?php if (!empty($billing_address['street'])) { echo $billing_address['street']; } ?>" class="drl-register-input input-text required" placeholder="Primary Street (No P. O. Boxes)">
                      </div>
                   </div>
                   <div class="field field-billing_city drl-width-input">
                      <label class="label drl-required-astr" for="billing_city"><span>City</span></label>
                      <div class="control">
                        <input type="text" id="billing_city" name="billing[city]" value="<?php if (!empty($billing_address['city'])) { echo $billing_address['city']; } ?>" class="drl-register-input input-text required" placeholder="Enter City">
                      </div>
                   </div>
                </div>

                <div class="drl-register">
                   <div class="field field-billing_state drl-width-input">
                      <label class="label drl-required-astr" for="billing_state"><span>State</span></label>
                      <div class="control">
                        <?php if (!empty($billing_address['region_id'])) {
                            $selected_company_region = $billing_address['region_id']; 
                        } else {
                            $selected_company_region = 0;
                        } ?>
                         <select id="billing_state" name="billing[state]" class="drl-register-input input-text required">
                            <option value="">Please select a region, state or province.</option>
                            <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                                <?php if($idx > 0) { ?>
                                    <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                                <?php } ?>
                            <?php } ?>
                         </select>
                      </div>
                   </div>
                   <div class="field field-billing_country drl-width-input">
                      <label class="label drl-required-astr" for="billing_country"><span>Country</span></label>
                      <div class="control">
                         <select id="billing_country" name="billing[country]" class="drl-register-input input-text required">
                             <option value="US" selected="">United States</option>
                         </select>
                      </div>
                   </div>
                </div>

                <div class="drl-register">
                   <div class="field field-billing_zip drl-width-input-half">
                      <label class="label drl-required-astr" for="billing_zip"><span>ZIP/Postal Code</span></label>
                      <div class="control">
                         <input type="text" id="billing_zip" name="billing[zip]" value="<?php if (!empty($billing_address['postcode'])) { echo $billing_address['postcode']; } ?>" minlength="5" maxlength="5" class="drl-register-input input-text validate-zip-us required validate-digits required" placeholder="Enter ZIP/Postal Code">
                      </div>
                   </div>
                   <div class="field field-billing_telephone drl-width-input-half">
                      <label class="label drl-required-astr" for="billing_telephone"><span>Phone Number</span></label>
                      <div class="control">
                         <input type="text" id="billing_phone" name="billing[phone]" value="<?php if (!empty($billing_address['telephone'])) { echo $billing_address['telephone']; } ?>" minlength="10" maxlength="10" class="drl-with-coun drl-register-input-number input-text required validate-digits required" placeholder="Enter Phone Number">
                      </div>
                   </div>
                </div>

                <div class="drl-register">
                   <div class="field field-billing_fax drl-width-input-half">
                      <label class="label" for="billing_fax"><span>FAX Number</span></label>
                      <div class="control">
                         <input type="text" id="billing_fax_number" name="billing[fax]" value="<?php if (!empty($billing_address['fax'])) { echo $billing_address['fax']; } ?>" class="drl-register-input input-text validate-digits" placeholder="Enter FAX Number">
                      </div>
                   </div>
                </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-billing-add-form">
               <div class="drl-bill-head">
                  <legend class="drl-legends-second"><span class="drl-main-middle-head">
                     <?= $block->escapeHtml(__('Primary Shipping Address')) ?></span>
                  </legend>
               </div>
            </div>

            <?php
                $shipping_address = [];
                $shipping_address = $block->getShippingAddress();
            ?>
            <div id="shipping-address-block">
                <input type="hidden" id="state_license_id_row" name="shipping_address[row_id]" value="">
                <input type="hidden" id="state_license_status" name="shipping_address[state_license_status]" value="<?php if (!empty($shipping_address['state_license_status'])) { echo $shipping_address['state_license_status']; } ?>">
                <br>
                  <div class="drl-register">
                   <div class="field field-state_license_id drl-width-input">
                      <label class="label drl-required-astr" for="state_license_id"><span>State License Id</span></label>
                      <div class="control">
                         <input type="text" id="state_license_id" name="shipping[state_license_id]" autocomplete="off" value="<?php if (!empty($shipping_address['state_license_id'])) { echo $shipping_address['state_license_id']; } ?>" class="validate-medpro-license drl-register-input input-text required" placeholder="Enter State License Id">
                      </div>
                   </div>
                   <div class="field field-dea_license_id drl-width-input">
                      <label class="label" for="dea_license_id"><span>DEA License Id</span></label>
                      <div class="control">
                        <input type="text" id="dea_license_id" name="shipping[dea_license_id]" value="<?php if (!empty($shipping_address['dea_license_id'])) { echo $shipping_address['dea_license_id']; } ?>" class="drl-register-input input-text" placeholder="DEA License Id">
                      </div>
                   </div>
                </div>
                <?php
                  $state_license_uploaded = '';
                  if (!empty($shipping_address['state_license_upload'])) {
                    $state_license_uploaded = md5($shipping_address['state_license_upload']);
                  }
                ?>
                <div class="drl-register">
                   <div class="field  field-state_license_upload drl-width-input">
                      <label class="label drl-required-astr" for="state_license_upload"><span>Upload State License</span></label>
                      <div class="control">
                         <input type="file" id="state_license_upload" name="shipping[state_license_upload]" value="" class="drl-register-input input-file <?php if($state_license_uploaded == ''){ ?> required <?php } ?>">
                         <input type="hidden" id="state_license_upload_value" name="state_license_upload_value" value="<?php echo md5($state_license_uploaded); ?>">
                      </div>
                   </div>
                   <div class="field  field-dea_license_upload drl-width-input">
                      <label class="label" for="dea_license_upload"><span>Upload DEA License</span></label>
                      <div class="control">
                         <input type="file" id="dea_license_upload" name="shipping[dea_license_upload]" value="" class="input-file drl-register-input">
                         <input type="hidden" id="dea_license_upload_value" name="dea_license_upload_value" value="<?php if (!empty($shipping_address['dea_license_upload'])) { echo md5($shipping_address['dea_license_upload']); } ?>">
                      </div>
                   </div>
                </div>
                <div class="drl-register">
                   <div class="field field-legal_business_name drl-width-input">
                      <label class="label drl-required-astr" for="legal_business_name"><span>State License Expire Date</span></label>
                      <div class="control">
                         <input type="text" id="state_license_expiry" name="shipping[state_license_expiry]" autocomplete="off" value="<?php if (!empty($shipping_address['state_license_expiry'])) { echo date("Y-m-d", strtotime($shipping_address['state_license_expiry'])); } ?>" readonly class="drl-register-input required input-text" placeholder="Enter State License Expire Date">
                      </div>
                   </div>
                   <div class="field field-dea_license_expiry drl-width-input">
                      <label class="label" for="dea_license_expiry"><span>DEA License Expire Date</span></label>
                      <div class="control">
                        <input type="text" id="dea_license_expiry" name="shipping[dea_license_expiry]" value="<?php if (!empty($shipping_address['dea_license_expiry'])) { echo $shipping_address['dea_license_expiry']; } ?>" class=" dea_datepicker drl-register-input input-text" placeholder="DEA License Expire Date">
                      </div>
                   </div>
                </div>
                  <div class="drl-register">
                     <div class="field field-shipping_street drl-width-input">
                        <label class="drl-required-astr label" for="shipping_street"><span>Primary Street (No P. O. Boxes)</span></label>
                        <div class="control">
                           <input type="text" id="shipping_street" name="shipping[street]" value="<?php if (!empty($shipping_address['street'])) { echo $shipping_address['street']; } ?>" class="drl-register-input input-text required" placeholder="Primary Street (No P. O. Boxes)">
                        </div>
                     </div>
                     <div class="field field-shipping_city drl-width-input">
                        <label class="drl-required-astr label" for="shipping_city"><span>City</span></label>
                        <div class="control">
                          <input type="text" id="shipping_city" name="shipping[city]" value="<?php if (!empty($shipping_address['city'])) { echo $shipping_address['city']; } ?>" class="drl-register-input input-text required" placeholder="Enter City">
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_state drl-width-input">
                        <label class="drl-required-astr label" for="shipping_state"><span>State</span></label>
                        <div class="control">
                          <?php if (!empty($shipping_address['region_id'])) {
                              $selected_company_region = $shipping_address['region_id'];
                          } else {
                              $selected_company_region = 0;
                          } ?>
                           <select id="shipping_state" name="shipping[state]" class="drl-register-input input-text required">
                              <option value="">Please select a region, state or province.</option>
                              <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                                  <?php if($idx > 0) { ?>
                                      <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                                  <?php } ?>
                              <?php } ?>
                           </select>
                        </div>
                     </div>
                     <div class="field field-shipping_country drl-width-input">
                        <label class="drl-required-astr label" for="shipping_country"><span>Country</span></label>
                        <div class="control">
                           <select id="shipping_country" name="shipping[country]" class="drl-register-input input-text required">
                               <option value="US" selected="">United States</option>
                           </select>
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_zip drl-width-input-half">
                        <label class="drl-required-astr label" for="shipping_zip"><span>ZIP/Postal Code</span></label>
                        <div class="control">
                           <input type="text" id="shipping_zip" name="shipping[zip]" value="<?php if (!empty($shipping_address['postcode'])) { echo $shipping_address['postcode']; } ?>" minlength="5" maxlength="5" class="drl-register-input input-text validate-zip-us required validate-digits required" placeholder="Enter ZIP/Postal Code">
                        </div>
                     </div>
                     <div class="field field-shipping_telephone drl-width-input-half">
                        <label class="drl-required-astr label" for="shipping_telephone"><span>Phone Number</span></label>
                        <div class="control">
                           <input type="text" id="shipping_phone" name="shipping[phone]" value="<?php if (!empty($shipping_address['telephone'])) { echo $shipping_address['telephone']; } ?>" minlength="10" maxlength="10" class="drl-with-coun drl-register-input-number input-text required validate-digits required" placeholder="Enter Phone Number">
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_fax drl-width-input-half">
                        <label class="label" for="shipping_fax"><span>FAX Number</span></label>
                        <div class="control">
                           <input type="text" id="shipping_fax_number" name="shipping[fax]" value="<?php if (!empty($shipping_address['fax'])) { echo $shipping_address['fax']; } ?>" class="drl-register-input input-text validate-digits" placeholder="Enter FAX Number">
                        </div>
                     </div>
                  </div>
              <?php
                  $other_shipping_address_data = [];
                  $other_shipping_address_data = $block->getOtherShippingAddress();
              ?>
              <?php $other_address_row = 0; ?>
              <?php foreach($other_shipping_address_data as $other_shipping_address) { ?>
                <div id="shipping-address-row-<?php echo $other_address_row; ?>">
                  <input type="hidden" id="other_address_id_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][address_id]" value="<?php if (!empty($other_shipping_address->getId())) { echo $other_shipping_address->getId(); } ?>">
                  <input type="hidden" id="state_license_id_<?php echo $other_address_row; ?>_row" name="other_address[<?php echo $other_address_row; ?>][row_id]" value="<?php echo $other_address_row; ?>">
                  <input type="hidden" id="state_license_status_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][state_license_status]" autocomplete="off" value="<?php if (!empty($other_shipping_address->getCustomAttribute("state_license_status"))) { echo $other_shipping_address->getCustomAttribute("state_license_status")->getValue(); } ?>" >
                  <div class="drl-hr-line"></div>
                    <div class="drl-billing-add-form">
                      <div class="drl-bill-head">
                        <legend class="drl-legends-second">
                          <span class="drl-main-middle-head">Additional Shipping Address <?php echo $other_address_row+1; ?></span>
                        </legend>
                    </div>
                    <div class="drl-switch-add-bill"><div class="drl-switch-field"><button type="button" data-toggle="tooltip" title="Remove" class="remove-address-block btn btn-danger"><i class="fa fa-minus-circle"></i></button></div></div>
                  </div>
                  <div class="drl-hr-line"></div>
                  <div class="drl-register">
                   <div class="field field-state_license_id drl-width-input">
                      <label class="drl-required-astr label" for="state_license_id"><span>State License Id</span></label>
                      <div class="control">
                         <input type="text" id="state_license_id_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][state_license_id]" autocomplete="off" value="<?php if (!empty($other_shipping_address->getCustomAttribute("state_license_id"))) { echo $other_shipping_address->getCustomAttribute("state_license_id")->getValue(); } ?>" class="validate-medpro-license drl-register-input input-text required" placeholder="Enter State License Id">
                      </div>
                   </div>
                   <div class="field field-dea_license_id drl-width-input">
                      <label class="label" for="dea_license_id"><span>DEA License Id</span></label>
                      <div class="control">
                        <input type="text" id="dea_license_id_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][dea_license_id]" value="<?php if (!empty($other_shipping_address->getCustomAttribute("dea_license_id"))) { echo $other_shipping_address->getCustomAttribute("dea_license_id")->getValue(); } ?>" class="drl-register-input input-text" placeholder="DEA License Id">
                      </div>
                   </div>
                </div>
                <?php
                  $state_license_uploaded = '';
                  if (!empty($other_shipping_address->getCustomAttribute("state_license_upload"))) {
                    $state_license_uploaded = $other_shipping_address->getCustomAttribute("state_license_upload")->getValue();
                  }
                ?>
                <div class="drl-register">
                   <div class="field  field-state_license_upload drl-width-input">
                      <label class="label drl-required-astr" for="state_license_upload"><span>Upload State License</span></label>
                      <div class="control">
                         <input type="file" id="state_license_upload_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][state_license_upload]" value="" class="drl-register-input input-file <?php if($state_license_uploaded != ''){ ?>required<?php } ?>">
                         <input type="hidden" id="state_license_upload_value" name="state_license_upload_value" value="<?php echo md5($state_license_uploaded); ?>">
                      </div>
                   </div>
                   <div class="field  field-dea_license_upload drl-width-input">
                      <label class="label" for="dea_license_upload"><span>Upload DEA License</span></label>
                      <div class="control">
                         <input type="file" id="dea_license_upload_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][dea_license_upload]" value="" class="input-file drl-register-input">
                         <input type="hidden" id="dea_license_upload_value" name="dea_license_upload_value" value="<?php if (!empty($other_shipping_address->getCustomAttribute("dea_license_upload"))) { echo $other_shipping_address->getCustomAttribute("dea_license_upload")->getValue(); } ?>">
                      </div>
                   </div>
                </div>
                <div class="drl-register">
                   <div class="field field-legal_business_name drl-width-input">
                      <label class="label drl-required-astr" for="legal_business_name"><span>State License Expire</span></label>
                      <div class="control">
                         <input type="text" id="state_license_expiry_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][state_license_expiry]" autocomplete="off" value="<?php if (!empty($other_shipping_address->getCustomAttribute("state_license_expiry"))) { echo date("Y-m-d", strtotime($other_shipping_address->getCustomAttribute("state_license_expiry")->getValue())); } ?>" readonly class="drl-register-input input-text" placeholder="Enter State License Expire Date">
                      </div>
                   </div>
                   <div class="field field-dea_license_expiry drl-width-input">
                      <label class="label" for="dea_license_expiry"><span>DEA License Expire Date</span></label>
                      <div class="control">
                        <input type="text" id="dea_license_expiry_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][dea_license_expiry]" value="<?php if (!empty($other_shipping_address->getCustomAttribute("dea_license_expiry"))) { echo $other_shipping_address->getCustomAttribute("dea_license_expiry")->getValue(); } ?>" class="dea_datepicker drl-register-input input-text" placeholder="DEA License Expire Date">
                      </div>
                   </div>
                </div>
                  <div class="drl-register">
                     <div class="field field-shipping_street drl-width-input">
                        <label class="drl-required-astr label" for="shipping_street"><span>Primary Street (No P. O. Boxes)</span></label>
                        <div class="control">
                           <input type="text" id="shipping_street_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][street]" value="<?php if (!empty($other_shipping_address->getStreet())) { echo implode(", ", $other_shipping_address->getStreet()); } ?>" class="drl-register-input input-text required" placeholder="Primary Street (No P. O. Boxes)">
                        </div>
                     </div>
                     <div class="field field-shipping_city drl-width-input">
                        <label class="drl-required-astr label" for="shipping_city"><span>City</span></label>
                        <div class="control">
                          <input type="text" id="shipping_city_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][city]" value="<?php if (!empty($other_shipping_address->getCity())) { echo $other_shipping_address->getCity(); } ?>" class="drl-register-input input-text required" placeholder="Enter City">
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_state drl-width-input">
                        <label class="drl-required-astr label" for="shipping_state"><span>State</span></label>
                        <div class="control">
                          <?php if (!empty($other_shipping_address->getRegionId())) {
                              $selected_company_region = $other_shipping_address->getRegionId();
                          } else {
                              $selected_company_region = 0;
                          } ?>
                           <select id="shipping_state_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][state]" class="drl-register-input input-text required">
                              <option value="">Please select a region, state or province.</option>
                              <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                                  <?php if($idx > 0) { ?>
                                      <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                                  <?php } ?>
                              <?php } ?>
                           </select>
                        </div>
                     </div>
                     <div class="field field-shipping_country drl-width-input">
                        <label class="drl-required-astr label" for="shipping_country"><span>Country</span></label>
                        <div class="control">
                           <select id="shipping_country_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][country]" class="drl-register-input input-text required">
                               <option value="US" selected="">United States</option>
                           </select>
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_zip drl-width-input-half">
                        <label class="drl-required-astr label" for="shipping_zip"><span>ZIP/Postal Code</span></label>
                        <div class="control">
                           <input type="text" id="shipping_zip_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][zip]" value="<?php if (!empty($other_shipping_address->getPostcode())) { echo $other_shipping_address->getPostcode(); } ?>" minlength="5" maxlength="5" class="drl-register-input input-text validate-zip-us required validate-digits" placeholder="Enter ZIP/Postal Code">
                        </div>
                     </div>
                     <div class="field field-shipping_telephone drl-width-input-half">
                        <label class="label" for="shipping_telephone"><span>Phone Number</span></label>
                        <div class="control">
                           <input type="text" id="shipping_phone_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][phone]" value="<?php if (!empty($other_shipping_address->getTelephone())) { echo $other_shipping_address->getTelephone(); } ?>" minlength="10" maxlength="10" class="drl-register-input input-text required validate-digits" placeholder="Enter Phone Number">
                        </div>
                     </div>
                  </div>

                  <div class="drl-register">
                     <div class="field field-shipping_fax drl-width-input-half">
                        <label class="label" for="shipping_fax"><span>FAX Number</span></label>
                        <div class="control">
                           <input type="text" id="shipping_fax_number_<?php echo $other_address_row; ?>" name="other_address[<?php echo $other_address_row; ?>][fax]" value="<?php if (!empty($other_shipping_address->getFax())) { echo $other_shipping_address->getFax(); } ?>" class="drl-register-input input-text validate-digits" placeholder="Enter FAX Number">
                        </div>
                     </div>
                  </div>
                </div>
                <?php $other_address_row = $other_address_row+1; ?>

              <?php } ?>
            </div>
            <div class="drl-add-ship-addres">
                 <button type="button" data-toggle="tooltip" title="Add" class="add-shipping-address btn btn-primary">Add Another Shipping Address</button>
             </div>
            <div class="drl-hr-line"></div>
            <div class="drl-register">
               <div class="field field-contact_person drl-width-input-half">
                  <label class="label" for="contact_person"><span>Have you been in touch with Dr Reddys?</span></label>
                 
          <!--        <div class="drl-register-contact-radio">
                    <input type="radio" name="user-type" value="yes" checked/> <span class="yes">Yes</span>
                    <input type="radio" name="user-type" value="no" /><span class="no"> No </span>
                 </div> -->

               <div class="control drl-checkbox-y-n">
                  <input class="checkbox-tools edi-capabilities" id="user-to1" value="yes" type="radio" name="user-type" checked>
                  <label class="for-checkbox-tools" for="user-to1">
                  Yes
                  </label>
                  <input class="checkbox-tools edi-capabilities" id="user-to2" value="no" type="radio" name="user-type">
                  <label class="for-checkbox-tools" for="user-to2">
                  No
                  </label>
               </div>
                  <div class="control showstore" id="showstore">
                     <label class="label drl-required-astr" for="contact_person"><span>Enter Name</span></label>
                     <input type="text" id="contact_person" name="contact_person" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("contact_person"))) { echo $block->getCustomer()->getCustomAttribute("contact_person")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Enter Name *">
                  </div>
               </div>
            </div>
            <!--  <p>(*) Mandatory</p> -->
            <div class="drl-hr-line"></div>
         </div>
      </fieldset>
      <h3>
         <?= $block->escapeHtml(__('Company Info')) ?>
      </h3>
      <fieldset class="fieldset info drl-company-legal-info">
         <div id="ajax-field-1">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="steps_status" value="2" />
            <legend class="drl-legend"><span>
               <?= $block->escapeHtml(__('Company Legal Information')) ?></span>
            </legend>
            <br>
            <div class="drl-heading-space">
               <legend class="drl-legends-second"><span>
                  <?= $block->escapeHtml(__('Corporate')) ?></span>
               </legend>
               <legend class="drl-legends-third"><span>
                  <?= $block->escapeHtml(__('Please enter the contact details of Corporate')) ?></span>
               </legend>
            </div>
            <div class="drl-register">
               <div class="field field-corporate_contact_name drl-width-input">
                  <label class="drl-required-astr label" for="corporate_contact_name"><span>Corporate Contact Name </span></label>
                  <div class="control">
                     <input type="text" id="corporate_contact_name" name="corporate_contact_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("corporate_contact_name"))) { echo $block->getCustomer()->getCustomAttribute("corporate_contact_name")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Corporate Contact Name">
                  </div>
               </div>
               <div class="field field-corporate_contact_phone_number drl-width-input">
                  <label class="drl-required-astr label" for="corporate_contact_phone_number"><span>Corporate Contact Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="corporate_contact_phone_number" name="corporate_contact_phone_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("corporate_contact_phone_number"))) { echo $block->getCustomer()->getCustomAttribute("corporate_contact_phone_number")->getValue(); } ?>" class="drl-with-coun drl-register-input-number input-text validate-digits required" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-corporate_contact_email_address drl-width-input-half">
                  <label class="drl-required-astr label" for="corporate_contact_email_address"><span>Corporate Contact E-mail Address </span></label>
                  <div class="control">
                     <input type="text" id="corporate_contact_email_address" name="corporate_contact_email_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("corporate_contact_email_address"))) { echo $block->getCustomer()->getCustomAttribute("corporate_contact_email_address")->getValue(); } ?>" class="drl-register-input input-text validate-email required" placeholder="Enter Corporate Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-heading-space">
               <legend class="drl-legends-second"><span>
                  <?= $block->escapeHtml(__('Purchasing')) ?></span>
               </legend>
               <legend class="drl-legends-third"><span>
                  <?= $block->escapeHtml(__('Please enter the contact details of Purchasing')) ?></span>
               </legend>
            </div>
            <div class="drl-register">
               <div class="field field-purchasing_contact_name drl-width-input">
                  <label class="drl-required-astr label" for="purchasing_contact_name"><span>Purchasing Contact Name </span></label>
                  <div class="control">
                     <input type="text" id="purchasing_contact_name" name="purchasing_contact_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("purchasing_contact_name"))) { echo $block->getCustomer()->getCustomAttribute("purchasing_contact_name")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Purchasing Contact Name">
                  </div>
               </div>
               <div class="field field-purchasing_contact_phone_number drl-width-input">
                  <label class="drl-required-astr label" for="purchasing_contact_phone_number"><span>Purchasing Contact Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="purchasing_contact_phone_number" name="purchasing_contact_phone_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("purchasing_contact_phone_number"))) { echo $block->getCustomer()->getCustomAttribute("purchasing_contact_phone_number")->getValue(); } ?>" class="drl-with-coun drl-register-input-number input-text validate-digits required" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-purchasing_contact_email_address drl-width-input-half">
                  <label class="drl-required-astr label" for="purchasing_contact_email_address"><span>Purchasing Contact E-mail Address </span></label>
                  <div class="control">
                     <input type="text" id="purchasing_contact_email_address" name="purchasing_contact_email_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("purchasing_contact_email_address"))) { echo $block->getCustomer()->getCustomAttribute("purchasing_contact_email_address")->getValue(); } ?>" class="drl-register-input input-text validate-email required" placeholder="Enter Contact Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-heading-space">
               <legend class="drl-legends-second"><span>
                  <?= $block->escapeHtml(__('Account payable')) ?></span>
               </legend>
               <legend class="drl-legends-third"><span>
                  <?= $block->escapeHtml(__('Please enter the contact details of payable Account')) ?></span>
               </legend>
            </div>
            <div class="drl-register">
               <div class="field field-accounts_payable_contact_name drl-width-input">
                  <label class="drl-required-astr label" for="accounts_payable_contact_name"><span>Accounts Payable Contact Name </span></label>
                  <div class="control">
                     <input type="text" id="accounts_payable_contact_name" name="accounts_payable_contact_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("accounts_payable_contact_name"))) { echo $block->getCustomer()->getCustomAttribute("accounts_payable_contact_name")->getValue(); } ?>" class="drl-register-input input-text drl-register-input required" placeholder="Enter Account payable Contact Name">
                  </div>
               </div>
               <div class="field field-ap_contact_phone_number drl-width-input">
                  <label class="drl-required-astr label" for="ap_contact_phone_number"><span>AP Contact Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="ap_contact_phone_number" name="ap_contact_phone_number" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("ap_contact_phone_number"))) { echo $block->getCustomer()->getCustomAttribute("ap_contact_phone_number")->getValue(); } ?>" class="drl-with-coun input-text validate-digits drl-register-input-number required" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-ap_email_address drl-width-input-half">
                  <label class="drl-required-astr label" for="ap_email_address"><span>AP E-mail Address </span></label>
                  <div class="control">
                     <input type="text" id="ap_email_address" name="ap_email_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("ap_email_address"))) { echo $block->getCustomer()->getCustomAttribute("ap_email_address")->getValue(); } ?>" class="input-text validate-email drl-register-input required" placeholder="Enter Account payable Contact Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-heading-space">
               <legend class="drl-legends-second"><span>
                  <?= $block->escapeHtml(__('Electronic Data Interchange (EDI)')) ?></span>
               </legend>
               <legend class="drl-legends-third"><span>
                  <?= $block->escapeHtml(__('Please enter the contact details of EDI')) ?></span>
               </legend>
            </div>
            <div class="drl-register">
               <div class="field field-edi_contact_name drl-width-input">
                  <label class="drl-required-astr label" for="edi_contact_name"><span>EDI Contact Name </span></label>
                  <div class="control">
                     <input type="text" id="edi_contact_name" name="edi_contact_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("edi_contact_name"))) { echo $block->getCustomer()->getCustomAttribute("edi_contact_name")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter EDI Contact Name">
                  </div>
               </div>
               <div class="field field-edi_contact_phone drl-width-input">
                  <label class="drl-required-astr label" for="edi_contact_phone"><span>EDI Contact Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="edi_contact_phone" name="edi_contact_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("edi_contact_phone"))) { echo $block->getCustomer()->getCustomAttribute("edi_contact_phone")->getValue(); } ?>" class="input-text validate-digits drl-register-input-number required drl-with-coun" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-edi_contact_email drl-width-input-half">
                  <label class="drl-required-astr label" for="edi_contact_email"><span>EDI Contact E-mail Address </span></label>
                  <div class="control">
                     <input type="text" id="edi_contact_email" name="edi_contact_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("edi_contact_email"))) { echo $block->getCustomer()->getCustomAttribute("edi_contact_email")->getValue(); } ?>" class="input-text validate-email drl-register-input required" placeholder="Enter EDI Contact Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-heading-space">
               <legend class="drl-legends-second"><span>
                  <?= $block->escapeHtml(__('Shipment Contact')) ?></span>
               </legend>
               <legend class="drl-legends-third"><span>
                  <?= $block->escapeHtml(__('Please enter the contact details of Shipment Contact')) ?></span>
               </legend>
            </div>
            <div class="drl-register">
               <div class="field field-ship_contact_name drl-width-input">
                  <label class="label" for="ship_contact_name"><span>Shipment Contact Name</span></label>
                  <div class="control">
                     <input type="text" id="ship_contact_name" name="ship_contact_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("ship_contact_name"))) { echo $block->getCustomer()->getCustomAttribute("ship_contact_name")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Shipment Contact Name">
                  </div>
               </div>
               <div class="field field-ship_contact_phone drl-width-input">
                  <label class="label" for="ship_contact_phone"><span>Shipment Contact Phone Number</span></label>
                  <div class="control">
                     <input type="text" id="ship_contact_phone" name="ship_contact_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("ship_contact_phone"))) { echo $block->getCustomer()->getCustomAttribute("ship_contact_phone")->getValue(); } ?>" class="drl-register-input-number input-text validate-digits drl-with-coun" minlength="10" maxlength="10" placeholder="Enter Shipment Phone Name">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-ship_contact_email drl-width-input-half">
                  <label class="label" for="ship_contact_email"><span>Shipment Contact E-mail Address</span></label>
                  <div class="control">
                     <input type="text" id="ship_contact_email" name="ship_contact_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("ship_contact_email"))) { echo $block->getCustomer()->getCustomAttribute("ship_contact_email")->getValue(); } ?>" class="drl-register-input input-text validate-email" placeholder="Enter Shipment Contact E-mail Address">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
         </div>
      </fieldset>
      <h3>
         <?= $block->escapeHtml(__('Business Identification')) ?>
      </h3>
      <fieldset class="fieldset info drl-business-ident">
         <div id="ajax-field-2">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="steps_status" value="3" />
            <legend class="drl-legend"><span>
               <?= $block->escapeHtml(__('Business Identification')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field field-business_type drl-width-input">
                  <label class="drl-required-astr label" for="business_type"><span>Type of Business </span></label>
                  <div class="control">
                     <?php
                     $business_type = '';
                      if (!empty($block->getCustomer()->getCustomAttribute("business_type"))) {
                            $business_type =  $block->getCustomer()->getCustomAttribute("business_type")->getValue();
                      }
                      ?>
                     <select id="business_type" name="business_type" class="drl-register-input required">
                        <option value="" >Select a Business</option>
                        <?php foreach($block->getBusinessTypes() as $business_type_data) { ?>tests
                          <option value="<?php echo $business_type_data['value']; ?>" <?php if($business_type == $business_type_data['value']){ ?> selected="selected"<?php } ?>><?php echo $business_type_data['label']; ?></option>
                        <?php } ?>
                     </select>
                  </div>
               </div>
               <div class="field field-business_other drl-width-input">
                  <label class="label" for="business_other"><span>If Type of Business is “Other”, Please Provide Information </span></label>
                  <div class="control">
                     <input type="text" id="business_other" name="business_other" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("business_other"))) { echo $block->getCustomer()->getCustomAttribute("business_other")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Information">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-federal_taxid drl-width-input-half">
                  <label class="drl-required-astr label" for="federal_taxid"><span>Federal Tax ID </span></label>
                  <div class="control">
                     <input type="text" id="federal_taxid" name="federal_taxid" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("federal_taxid"))) { echo $block->getCustomer()->getCustomAttribute("federal_taxid")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="12 - 1234567">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <legend class="drl-legends-second"><span>
               <?= $block->escapeHtml(__('Upload Documents')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field  field-w9_form drl-width-input">
                  <label class="drl-required-astr label" for="w9_form"><span>Upload W-9 Form</span></label>
                  <div class="control">
                     <input type="file" id="w9_form" name="w9_form" value="" class="drl-register-input input-file">
                     <input type="hidden" class="required" id="w9_form_value" name="w9_form_value" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("w9_form"))) { echo md5($block->getCustomer()->getCustomAttribute("w9_form")->getValue()); } ?>">
                  </div>
               </div>
               <div class="field  field-financial drl-width-input">
                  <label class="label" for="financial"><span>Upload Latest Financials</span></label>
                  <div class="control">
                     <input type="file" id="financial" name="financial" value="" class="drl-register-input input-file">
                     <input type="hidden" id="financial_value" name="financial_value" value="">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <?php
            $edi_capabilities = 0;
            if (!empty($block->getCustomer()->getCustomAttribute("fill_edi_capabilities"))) {
              $edi_capabilities = $block->getCustomer()->getCustomAttribute("fill_edi_capabilities")->getValue();
            }
            ?>
            <div class="field field-edi_capabilities required">
               <label class="label drl-required-astr" for="edi_capabilities"><span>Does Your Company Have EDI Capabilities</span></label>
               <div class="control drl-checkbox-y-n">
                  <input class="checkbox-tools edi-capabilities" type="radio" name="tools" id="tool-1" <?php if($edi_capabilities == 1) { ?>checked="checked"<?php } ?>>
                  <label class="for-checkbox-tools" for="tool-1">
                  Yes
                  </label>
                  <input class="checkbox-tools edi-capabilities" type="radio" name="tools" id="tool-2" <?php if($edi_capabilities == 0) { ?>checked="checked"<?php } ?>>
                  <label class="for-checkbox-tools" for="tool-2">
                  No
                  </label>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-gln_no drl-width-input">
                  <label class="label" for="gln_no"><span>Please fill the EDI Capabilities</span></label>
                  <div class="control">
                    <textarea placeholder="Enter EDI Capabilities" class="drl-register-input input-text" id="fill_edi_capabilities drl-register-input" name="fill_edi_capabilities"><?php if (!empty($block->getCustomer()->getCustomAttribute("fill_edi_capabilities"))) { echo $block->getCustomer()->getCustomAttribute("fill_edi_capabilities")->getValue(); } ?></textarea>
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-register">
               <div class="field field-gln_no drl-width-input">
                  <label class="label" for="gln_no"><span>GLN Number</span></label>
                  <div class="control">
                     <input type="text" id="gln_no" name="gln_no" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("gln_no"))) { echo $block->getCustomer()->getCustomAttribute("gln_no")->getValue(); } ?>" class="input-text validate-digits drl-register-input" placeholder="Enter GLN Number">
                  </div>
               </div>
                <div class="field field-idn_affiliation drl-width-input">
                  <label class="label" for="idn_affiliation"><span>IDN Affiliation</span></label>
                  <div class="control">
                     <input type="text" id="idn_affiliation" name="idn_affiliation" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("idn_affiliation"))) { echo $block->getCustomer()->getCustomAttribute("idn_affiliation")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter IDN Affiliation">
                  </div>
               </div>

            </div>
            <div class="drl-register">
                <div class="field field-partof_organization drl-width-input required">
                  <label class="label drl-required-astr" for="partof_organization"><span>If Part of a GPO, Please Select GPO Name </span></label>
                  <div class="control">
                    <?php
                        $partof_organization = '';
                        if (!empty($block->getCustomer()->getCustomAttribute("partof_organization"))) {
                            $partof_organization =  $block->getCustomer()->getCustomAttribute("partof_organization")->getValue();
                        }
                    ?>
                     <select id="partof_organization" name="partof_organization" class="drl-register-input input-text required">
                        <option value="">Select GPO</option>
                        <?php foreach($block->getGpoList() as $gpo_list) { ?>tests
                          <option value="<?php echo $gpo_list['value']; ?>" <?php if($partof_organization == $gpo_list['value']){ ?> selected="selected"<?php } ?>><?php echo $gpo_list['label']; ?></option>
                        <?php } ?>
                     </select>
                  </div>
               </div>
               <div class="field field-gpo_others drl-width-input">
                  <label class="label" for="gpo_others"><span>Other GPO Name</span></label>
                  <div class="control">
                     <input type="text" id="gpo_others" name="gpo_others" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("gpo_others"))) { echo $block->getCustomer()->getCustomAttribute("gpo_others")->getValue(); } ?>" class="input-text  drl-register-input" placeholder="Enter Other GPO Name">
                  </div>
               </div>
            </div>
            <div class="drl-register">
                <div class="field field-partof_organization drl-width-input">
                  <label class="label drl-required-astr" for="disproportionate_hospital"><span>Are you disproportionate hospital?</span></label>
                   <div class="control">
                    <?php
                        $disproportionate_hospital = '';
                        if (!empty($block->getCustomer()->getCustomAttribute("disproportionate_hospital"))) {
                            $disproportionate_hospital =  $block->getCustomer()->getCustomAttribute("disproportionate_hospital")->getValue();
                        }
                    ?>
                      <select id="disproportionate_hospital" name="disproportionate_hospital" class="drl-register-input input-text required">
                         <option value="" selected="selected"></option>
                         <option value="0"<?php if($disproportionate_hospital == 0){ ?> selected="selected"<?php } ?>>No</option>
                         <option value="1"<?php if($disproportionate_hospital == 1){ ?> selected="selected"<?php } ?>>Yes</option>
                      </select>
                   </div>
               </div>
               <div class="field field-monthly_purchase drl-width-input">
                  <label class="label" for="monthly_purchase"><span>Expected Monthly Purchases </span></label>
                  <div class="control">
                     <input type="text" id="monthly_purchase" name="monthly_purchase" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("monthly_purchase"))) { echo $block->getCustomer()->getCustomAttribute("monthly_purchase")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Enter Expected Monthly Purchases">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
         </div>
      </fieldset>
      <h3>
         <?= $block->escapeHtml(__('Trade Info')) ?>
      </h3>
      <fieldset class="fieldset info drl-trade-info">
         <div id="ajax-field-3">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="steps_status" value="4" />
            <legend class="drl-legend"><span>
               <?= $block->escapeHtml(__('Trade Information')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field field-trade_businessname drl-width-input">
                  <label class="label drl-required-astr" for="trade_businessname"><span>Trade Reference Business Name</span></label>
                  <div class="control">
                     <input type="text" id="trade_businessname" name="trade_businessname" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_businessname"))) { echo $block->getCustomer()->getCustomAttribute("trade_businessname")->getValue(); } ?>" class="drl-register-input input-text required" placeholder="Enter Trade Reference Business Name">
                  </div>
               </div>
               <div class="field field-trade_phone drl-width-input">
                  <label class="label drl-required-astr" for="trade_phone"><span>Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="trade_phone" name="trade_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_phone"))) { echo $block->getCustomer()->getCustomAttribute("trade_phone")->getValue(); } ?>" class="drl-with-coun drl-register-input-number input-text validate-digits required" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-trade_email drl-width-input-half">
                  <label class="label drl-required-astr" for="trade_email"><span>E-mail Address</span></label>
                  <div class="control">
                     <input type="text" id="trade_email" name="trade_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_email"))) { echo $block->getCustomer()->getCustomAttribute("trade_email")->getValue(); } ?>" class="drl-register-input input-text validate-email required" placeholder="Enter Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <div class="drl-billing-add-form">
               <div class="drl-bill-head">
                  <legend class="drl-legends-second"><span class="drl-main-middle-head">
                     <?= $block->escapeHtml(__('Trade Address')) ?></span>
                  </legend>
               </div>
               <br>
               <div class="drl-switch-add-bill">
                  <div >
                     <span class="drl-legends-third drl-title-middle-toogle"> Same as Corporate Address</span>
                  </div>
                  <div class="drl-switch-field">
                     <label class="switch">
                     <input class="toogle-check" name="trade_as_corporate" id="trade_as_corporate" type="checkbox" checked />
                     <span class="slider round"></span>
                     </label>
                  </div>
               </div>
            </div>
            <div id="trade-add-form" style="display: none;">
               <div class="drl-register">
                  <div class="field field-trade_address drl-width-input">
                     <label class="label drl-required-astr" for="trade_address"><span>Street Address </span></label>
                     <div class="control">
                        <input type="text" id="trade_address" name="trade_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_address"))) { echo $block->getCustomer()->getCustomAttribute("trade_address")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Primary Street Address">
                     </div>
                  </div>
                  <div class="field field-trade_city drl-width-input">
                     <label class="label drl-required-astr" for="trade_city"><span>City</span></label>
                     <div class="control">
                        <input type="text" id="trade_city" name="trade_city" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_city"))) { echo $block->getCustomer()->getCustomAttribute("trade_city")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter City">
                     </div>
                  </div>
               </div>
               <div class="drl-register">
                  <div class="field field-trade_state drl-width-input">
                     <label class="label drl-required-astr" for="trade_state"><span>State/Province </span></label>
                      <div class="control">
                        <?php if (!empty($block->getCustomer()->getCustomAttribute("trade_state"))) {
                            $selected_company_region = $block->getCustomer()->getCustomAttribute("trade_state")->getValue();
                        } else {
                            $selected_company_region = 0;
                        } ?>
                         <select id="trade_state" name="trade_state" class="drl-register-input input-text required">
                            <option value="">Please select a region, state or province.</option>
                            <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                                <?php if($idx > 0) { ?>
                                    <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                                <?php } ?>
                            <?php } ?>
                         </select>
                      </div>
                  </div>
                   <div class="field field-trade_country drl-width-input">
                      <label class="label drl-required-astr" for="trade_country"><span>Country</span></label>
                      <div class="control">
                         <select id="trade_country" name="trade_country" class="drl-register-input input-text required">
                             <option value="US" selected="">United States</option>
                         </select>
                      </div>
                   </div>
               </div>
               <div class="drl-register">
                  <div class="field field-trade_zip drl-width-input-half">
                     <label class="label drl-required-astr" for="trade_zip"><span>Zip / Postal Code </span></label>
                     <div class="control">
                        <input type="text" id="trade_zip" name="trade_zip" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_zip"))) { echo $block->getCustomer()->getCustomAttribute("trade_zip")->getValue(); } ?>" minlength="5" maxlength="5" class="input-text drl-register-input validate-zip-us required" placeholder="Enter Zip / Postal Code">
                     </div>
                  </div>
                  <div class="field field-trade_fax drl-width-input-half">
                    <label class="label" for="trade_fax"><span>Fax Number </span></label>
                    <div class="control">
                       <input type="text" id="trade_fax" name="trade_fax" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("trade_fax"))) { echo $block->getCustomer()->getCustomAttribute("trade_fax")->getValue(); } ?>" class="input-text validate-digits drl-register-input" placeholder="Enter Fax Number">
                    </div>
                 </div>
              </div>
            </div>
            <div class="drl-hr-line"></div>
         </div>
      </fieldset>
      <h3>
         <?= $block->escapeHtml(__('Bank Info')) ?>
      </h3>
      <fieldset class="fieldset info drl-bank-info">
         <legend class="drl-legend"><span>
            <?= $block->escapeHtml(__('Bank Details')) ?></span>
         </legend>
         <br>
         <div id="ajax-field-4">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="steps_status" value="5" />
            <div class="drl-register">
               <div class="field field-bank_name drl-width-input">
                  <label class="label drl-required-astr" for="bank_name"><span>Bank Name </span></label>
                  <div class="control">
                     <input type="text" id="bank_name" name="bank_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_name"))) { echo $block->getCustomer()->getCustomAttribute("bank_name")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Bank Name">
                  </div>
               </div>
               <div class="field field-bank_contactname drl-width-input">
                  <label class="label drl-required-astr" for="bank_contactname"><span>Contact Person Name</span></label>
                  <div class="control">
                     <input type="text" id="bank_contactname" name="bank_contactname" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_contactname"))) { echo $block->getCustomer()->getCustomAttribute("bank_contactname")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Contact Person Name">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-bank_account drl-width-input">
                  <label class="label drl-required-astr" for="bank_account"><span>Account Number </span></label>
                  <div class="control">
                     <input type="text" id="bank_account" name="bank_account" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_account"))) { echo $block->getCustomer()->getCustomAttribute("bank_account")->getValue(); } ?>" class="input-text validate-digits drl-register-input required" placeholder="Enter Account Number">
                  </div>
               </div>
               <div class="field field-bank_phone drl-width-input">
                  <label class="label drl-required-astr" for="bank_phone"><span>Phone Number </span></label>
                  <div class="control">
                     <input type="text" id="bank_phone" name="bank_phone" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_phone"))) { echo $block->getCustomer()->getCustomAttribute("bank_phone")->getValue(); } ?>" class="drl-with-coun input-text validate-digits drl-register-input-number required" minlength="10" maxlength="10" placeholder="345 - 345 - 6545">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-bank_fax drl-width-input">
                  <label class="label" for="bank_fax"><span>Fax Number </span></label>
                  <div class="control">
                     <input type="text" id="bank_fax" name="bank_fax" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_fax"))) { echo $block->getCustomer()->getCustomAttribute("bank_fax")->getValue(); } ?>" class="input-text validate-digits drl-register-input" placeholder="Enter Fax Number">
                  </div>
               </div>
               <div class="field field-bank_contact_email_address drl-width-input">
                  <label class="drl-required-astr label" for="bank_contact_email_address"><span>Email Address </span></label>
                  <div class="control">
                     <input type="text" id="bank_email" name="bank_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_email"))) { echo $block->getCustomer()->getCustomAttribute("bank_email")->getValue(); } ?>" class="drl-register-input input-text validate-email required" placeholder="Enter Bank Email ID">
                  </div>
               </div>
            </div>
            <div class="drl-hr-line"></div>
            <legend class="drl-legends-second"><span>
               <?= $block->escapeHtml(__('Bank Address')) ?></span>
            </legend>
            <br>
            <div class="drl-register">
               <div class="field field-bank_address drl-width-input">
                  <label class="label drl-required-astr" for="bank_address"><span>Primary Street (No P. O. Boxes) </span></label>
                  <div class="control">
                     <input type="text" id="bank_address" name="bank_address" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_address"))) { echo $block->getCustomer()->getCustomAttribute("bank_address")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter Primary Street">
                  </div>
               </div>
               <div class="field field-bank_city drl-width-input">
                      <label class="label drl-required-astr" for="bank_city"><span>City </span></label>
                      <div class="control">
                        <input type="text" id="bank_city" name="bank_city" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_city"))) { echo $block->getCustomer()->getCustomAttribute("bank_city")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Enter City">
                   </div>
                </div>
            </div>
            <div class="drl-register">
               <div class="field field-bank_state drl-width-input">
                  <label class="label drl-required-astr" for="bank_state"><span>Select State </span></label>
                   <div class="control">
                    <?php if (!empty($block->getCustomer()->getCustomAttribute("bank_state"))) {
                        $selected_company_region = $block->getCustomer()->getCustomAttribute("bank_state")->getValue(); 
                    } else {
                        $selected_company_region = 0;
                    } ?>
                     <select id="bank_state" name="bank_state" class="drl-register-input input-text required">
                        <option value="">Please select a region, state or province.</option>
                        <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                            <?php if($idx > 0) { ?>
                                <option value="<?php echo $region['value']; ?>" <?php if($selected_company_region == $region['value']){ ?> selected="selected"<?php } ?>><?php echo $region['label']; ?></option>
                            <?php } ?>
                        <?php } ?>
                     </select>
                  </div>
               </div>
               <div class="field field-bank_country drl-width-input">
                  <label class="label drl-required-astr" for="bank_country"><span>Country</span></label>
                  <div class="control">
                     <select id="bank_country" name="bank_country" class="drl-register-input input-text required">
                         <option value="US" selected="">United States</option>
                     </select>
                  </div>
               </div>
           </div>
           <div class="drl-register">
               <div class="field field-bank_zip drl-width-input-half">
                  <label class="label drl-required-astr" for="bank_zip"><span>Zip / Postal Code </span></label>
                  <div class="control">
                     <input type="text" id="bank_zip" name="bank_zip" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("bank_zip"))) { echo $block->getCustomer()->getCustomAttribute("bank_zip")->getValue(); } ?>" minlength="5" maxlength="5" class="input-text drl-register-input validate-zip-us required" placeholder="Enter Zip / Postal Code">
                  </div>
               </div>
            </div>
             <div class="drl-hr-line"></div>
             <div class="drl-register">
               <div class="field field-i_agree drl-width-input-half">
                  <div class="control drl-tickbox">
                     <input type="checkbox" id="i_agree" name="i_agree" value="1" class="input-checkbox required">
                     <label class="label drl-required-astr" for="i_agree"><span>I accept the&nbsp;<a href="#" id="termcon" class="term-hyper">Terms and Conditions</a></span></label>
                  </div>
                   <div id="popup-modal" class="terms-conditon-drl" style="display:none;">
                   <p class="drl-terms-word">By clicking submit below, I hereby represent that I am authorized to submit this application and bind the business identified in this application, and that the information provided is for the purpose of obtaining credit and is warranted to be true. 
                    </p>
                    <p class="drl-terms-word">
                    The business identified in this application acknowledges that this request is for the extension of credit for commercial purposes only and is not intended for the extension of credit for personal, family or household purposes. 
                  </p>
                  <p class="drl-terms-word">
                    In order to protect individual identities, unless an individual is intending to act as a guarantor for purposes of securing credit and is required to provide guarantor information on this application, no personally identifying information (i.e. Social Security #, driver’s license #, bank account information, etc.) should be provided.
                    </p>
                    <p class="drl-terms-word">
                    The business identified in this application hereby authorizes all banks, financial institutions, trade reference sources, credit reporting agencies and others to release credit information.
                   </p>
                   <p class="drl-terms-word">
                    In the event of a conflict, the terms and conditions set forth above shall control over any terms and conditions set forth below.  </p>
                </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-agree_name drl-width-input">
                  <label class="label drl-required-astr" for="agree_name"><span>Name </span></label>
                  <div class="control">
                     <input type="text" id="agree_name" name="agree_name" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("agree_name"))) { echo $block->getCustomer()->getCustomAttribute("agree_name")->getValue(); } ?>" class="input-text drl-register-input required" placeholder="Name">
                  </div>
               </div>
                     <div class="field field-agree_email drl-width-input">
                  <label class="label drl-required-astr" for="agree_email"><span>Email </span></label>
                  <div class="control">
                     <input type="text" id="agree_email" name="agree_email" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("agree_email"))) { echo $block->getCustomer()->getCustomAttribute("agree_email")->getValue(); } ?>" class="input-text validate-email drl-register-input required" placeholder="Email">
                  </div>
               </div>
            </div>
            <div class="drl-register">
               <div class="field field-auth_signature drl-width-input">
                  <label class="label" for="auth_signature"><span>Authorized Signature </span></label>
                  <div class="control">
                     <input type="text" id="auth_signature" name="auth_signature" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("auth_signature"))) { echo $block->getCustomer()->getCustomAttribute("auth_signature")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Authorized Signature">
                  </div>
               </div>
                         <div class="field field-professional_title drl-width-input">
                  <label class="label" for="professional_title"><span>Professional Title </span></label>
                  <div class="control">
                     <input type="text" id="professional_title" name="professional_title" value="<?php if (!empty($block->getCustomer()->getCustomAttribute("professional_title"))) { echo $block->getCustomer()->getCustomAttribute("professional_title")->getValue(); } ?>" class="input-text drl-register-input" placeholder="Professional Title">
                  </div>
               </div>
            </div>
           
         </div>
      </fieldset>
   </form>
   <div id="oval-assit">
      <div class="oval-sub-first-panel">
         <label class="oval-one">Need Assistance?</label>
      </div>
      <div class="oval-sub">
         <label class="oval-two">Where can I find Tracking No?</label>
         <label class="oval-two">How can I get Packing Slips?</label>
         <label class="oval-two">How can I get Packing Slips?</label>
         <a href="<?php echo $this->getBaseUrl()."view-faqs"; ?>" class="need-asst-faq">View FAQ&nbsp; <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::img/drl-right-faq.png'); ?>' alt="Right Arrow"></a>
      </div>
      <div class="dotted-slash-drl"></div>
      <div class="oval-sub">
         <div class="oval-multi-line">
              <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/phone.svg'); ?>' alt="Phone">
            <div class="oval-drl-help">
               <p class="oval-three">Helpline</p>
               <a href="tel:+1-866-733-3952" class="oval-tel-drl">866-733-3952</a>
            </div>
         </div>
      </div>
      <div class="oval-sub">
         <div class="oval-multi-line">
            <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/email.svg'); ?>' alt="email">
            <div class="oval-drl-help">
               <p class="oval-three">Customer Care</p>
               <a href="mailto:customercare@drreddys.com" class="oval-tel-drl">customercare@drreddys.com</a>
            </div>
         </div>
      </div>
      <div class="oval-sub">
         <div class="oval-multi-line">
           <img src='<?php echo $this->getViewFileUrl('Ecomm_Register::images/email.svg'); ?>' alt="email">
            <div class="oval-drl-help">
               <p class="oval-three">Technical Support</p>
               <a href="mailto:Direct@drreddys.com" class="oval-tel-drl">Direct@drreddys.com</a>
            </div>
         </div>
      </div>
   </div>
</div>
<div id="register-success"></div>
<script>
   require([
       'jquery',
       'mage/url',
       'Magento_Ui/js/modal/modal',
       'stepsjs',
       'drlnumberjs'
   ], function($, url, modal) {


       var form = $("#form-validate").show();

       form.steps({
           headerTag: "h3",
           bodyTag: "fieldset",
           transitionEffect: "slideLeft",
           theme: 'dots',
           labels: {
               next: "Save & Continue",
               previous: "Previous",
               finish: "Create Account"
           },
          onInit: function (event, currentIndex, newIndex) {
            //alert(currentIndex+'-'+newIndex);
            $('.actions > ul > li:first-child').attr('style', 'display:none');
          },
          onStepChanging: function(event, currentIndex, newIndex) {

            if (newIndex == 0) {
                $('.actions > ul > li:first-child').attr('style', 'display:none');
            }

            // Allways allow previous action even if the current form is not valid!
            if (currentIndex > newIndex)
            {
                return true;
            }

              form.validate().settings.ignore = ":disabled,:hidden";
              /*alert(currentIndex+'-'+newIndex);*/

              if (form.valid()) {
                /*//stop submit the form, we will post it manually.
                //event.preventDefault();

                // Get form
                var formid = $('#form-validate')[0];

                // Create an FormData object
                var data = new FormData(formid);*/

                // If you want to add an extra field for the FormData
                //data.append("CustomField", "This is some extra data, testing");

                if (newIndex > 0) {
                    $('.actions > ul > li:first-child').attr('style', 'display:block');
                } else {
                    $('.actions > ul > li:first-child').attr('style', 'display:none');
                }


                   $.ajax({
                        url: url.build('customer/account/updatePost'),
                        type: 'post',
                        /*enctype: 'multipart/form-data',
                        processData: false,  // Important!
                        contentType: false,
                        cache: false,*/
                        data: $('#ajax-field-' + currentIndex + ' input[type=\'text\'], #ajax-field-' + currentIndex + ' input[type=\'hidden\'], #ajax-field-' + currentIndex + ' input[type=\'checkbox\']:checked, #ajax-field-' + currentIndex + ' input[type=\'radio\']:checked, #ajax-field-' + currentIndex + ' textarea, #ajax-field-' + currentIndex + ' select'),
                        /*data: data,*/
                        dataType: 'json',
                        showLoader: true, //use for display loader
                        beforeSend: function() {},
                        success: function(json) {

                           if (json['status'] == 0) {
                               /*alert(json['msg']);*/
                               var options = {
                                   type: 'popup',
                                   title: '',
                                   responsive: true,
                                   innerScroll: false,
                                   clickableOverlay: false,
                                   buttons: [{
                                       text: $.mage.__('Continue'),
                                       class: 'success-notifications',
                                       click: function() {
                                           this.closeModal();
                                       }
                                   }]
                               };

                               $('#register-success').html('<div class="sucess-over-popup"><i class="far fa-times-circle icon-popup-reject"></i><div class="sucess-popup"><span>'+json['msg']+'</span></div></div>');


                               var popup = modal(options, $('#register-success'));
                               $("#register-success").modal("openModal");
                               return false;
                           } else {
                               /*alert(json['msg']);*/
                               return true;
                           }
                       },
                       error: function(xhr, ajaxOptions, thrownError) {
                           alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                       }
                   });
                   return form.valid();
               } else {
                   return form.valid();
               }
           },
           onFinished: function(event, currentIndex) {
               form.validate().settings.ignore = ":disabled,:hidden";

               if (form.valid()) {
                   $.ajax({
                       url: url.build('customer/account/updatePost'),
                       type: 'post',
                       data: $('#ajax-field-' + currentIndex + ' input[type=\'text\'], #ajax-field-' + currentIndex + ' input[type=\'hidden\'], #ajax-field-' + currentIndex + ' input[type=\'checkbox\']:checked, #ajax-field-' + currentIndex + ' input[type=\'radio\']:checked, #ajax-field-' + currentIndex + ' textarea, #ajax-field-' + currentIndex + ' select'),
                       dataType: 'json',
                       showLoader: true, //use for display loader
                       beforeSend: function() {},
                       success: function(json) {

                           if (json['status'] == 0) {
                               alert(json['msg']);
                           } else {
                               var options = {
                                   type: 'popup',
                                   title: '',
                                   responsive: true,
                                   innerScroll: false,
                                   clickableOverlay: false,
                                   buttons: [{
                                       text: $.mage.__('Continue'),
                                       class: 'success-notifications',
                                       click: function() {
                                            location = url.build('');
                                           this.closeModal();
                                       }
                                   }]
                               };

                               /*$('#register-success').html(json['msg']);*/
                               $('#register-success').html('<div class="sucess-over-popup"><i class="fas fa-check-circle icon-popup-sucess"></i><div class="sucess-popup"><span>Your Details Have Been Submitted Successfully! And Account is Currently Being Verified</span></div></div>');

                               var popup = modal(options, $('#register-success'));
                               $("#register-success").modal("openModal");
                           }
                       },
                       error: function(xhr, ajaxOptions, thrownError) {
                           alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                       }
                   });
                   return form.valid();
               } else {
                   return form.valid();
               }
           }
       });

        $(document).ready(function(){

            $('#billing_as_corporate').change(function(){
                if (this.checked) {
                    $('#billing_as_corporate').val(1);
                    $('#billing-address-block').hide('slow');
                } else {
                    $('#billing_as_corporate').val(0);
                    $('#billing-address-block').show('slow');
                }
            });

            $('#trade_as_corporate').change(function(){
                if (this.checked) {
                    $('#trade_as_corporate').val(1);
                    $('#trade-add-form').hide('slow');
                } else {
                    $('#trade_as_corporate').val(0);
                    $('#trade-add-form').show('slow');
                }
            });

            <?php if($block->getMedproStatus()) { ?>

              $(".validate-medpro-license" ).live( "change", function() {
                /*alert( "Handler for .change() called."+this.id );*/

                /*alert($("#"+this.id+"_row").val());*/

                var row_id = $("#"+this.id+"_row").val();

                var state_license_id = '';

                if(row_id == ''){
                  state_license_id = $("#"+this.id).val();
                } else {
                  state_license_id = $("#"+this.id).val();
                }

                /*alert(state_license_id);*/

                $.ajax({
                   url: url.build('customer/medpro/validate'),
                   type: 'post',
                   data: { state_license_id : state_license_id },
                   showLoader: true, //use for display loader
                   dataType: 'json',
                   beforeSend: function() {
                    //
                   },
                   success: function(json) {

                    if(json['success'] == true){

                      if(json['state_license_status'] == 'Y'){

                        /*alert("success");*/

                       if(row_id == ''){
                        if(json['state_license_expiry']!= '') {
                          $("#state_license_expiry").val(json['state_license_expiry']);
                        }
                       } else {
                        if(json['state_license_expiry']!= '') {
                          $("#state_license_expiry_"+row_id).val(json['state_license_expiry']);
                        }
                       }

                       if(row_id == ''){
                        if(json['state_license_status']!= '') {
                          $("#state_license_status").val(json['state_license_status']);
                        }
                       } else {
                        if(json['state_license_status']!= '') {
                          $("#state_license_status_"+row_id).val(json['state_license_status']);
                        }
                       }

                       /*if(row_id == ''){
                        if(json['dea_license_id']!= '') {
                          $("#dea_license_id").val(json['dea_license_id']);
                          //$("#dea_license_id").prop('readonly',true);
                        } else {
                          $("#dea_license_id").prop('readonly',false);
                        }
                       } else {
                        if(json['dea_license_id']!= '') {
                          $("#dea_license_id_"+row_id).val(json['dea_license_id']);
                          //$("#dea_license_id_"+row_id).prop('readonly',true);
                        } else {
                          $("#dea_license_id_"+row_id).prop('readonly',false);
                        }
                       }*/

                       if(row_id == ''){
                        $street = json['state_license_address']['line2'];
                        if(json['state_license_address']['line3'] != ''){
                          $street += ', '+json['state_license_address']['line2'];
                        }
                        if($street!=''){
                          $("#shipping_street").val($street);
                          $("#shipping_street").prop('readonly',true);
                        } else {
                          $("#shipping_street").prop('readonly',false);
                        }
                       } else {
                        $street = json['state_license_address']['line2'];
                        if(json['state_license_address']['line3'] != ''){
                          $street += ', '+json['state_license_address']['line2'];
                        }
                        if($street!=''){
                          $("#shipping_street_"+row_id).val($street);
                          $("#shipping_street_"+row_id).prop('readonly',true);
                        } else {
                          $("#shipping_street_"+row_id).prop('readonly',false);
                        }
                       }

                       if(row_id == ''){
                        if(json['state_license_address']['city']!= '') {
                          $("#shipping_city").val(json['state_license_address']['city']);
                          $("#shipping_city").prop('readonly',true);
                        } else {
                          $("#shipping_city").prop('readonly',false);
                        }
                       } else {
                        if(json['state_license_address']['city']!= '') {
                          $("#shipping_city_"+row_id).val(json['state_license_address']['city']);
                          $("#shipping_city_"+row_id).prop('readonly',true);
                        } else {
                          $("#shipping_city_"+row_id).prop('readonly',false);
                        }
                       }

                       if(row_id == ''){
                        if(json['state_license_address']['state_id']!= '') {
                          $("#shipping_state").val(json['state_license_address']['state_id']);
                          $("#shipping_state").attr("disabled", true);
                        } else {
                          $("#shipping_state").attr('disabled',false);
                        }
                       } else {
                        if(json['state_license_address']['state_id']!= '') {
                          $("#shipping_state_"+row_id).val(json['state_license_address']['state_id']);
                          $("#shipping_state_"+row_id).attr('disabled',true);
                        } else {
                          $("#shipping_state_"+row_id).attr('disabled',false);
                        }
                       }

                       if(row_id == ''){
                        if(json['state_license_address']['zip'] != ''){
                          $("#shipping_zip").val(json['state_license_address']['zip']);
                          $("#shipping_zip").prop('readonly',true);
                        } else {
                          $("#shipping_street").prop('readonly',false);
                        }
                       } else {
                        if(json['state_license_address']['zip'] != ''){
                          $("#shipping_zip_"+row_id).val(json['state_license_address']['zip']);
                          $("#shipping_zip_"+row_id).prop('readonly',true);
                        } else {
                          $("#shipping_zip_"+row_id).prop('readonly',false);
                        }
                       }

                      } else {

                        /* license is  invalid*/

                        if(row_id == ''){
                          $("#"+this.id).val('');
                        } else {
                          $("#"+this.id).val('');
                        }

                       if(row_id == ''){
                          $("#state_license_expiry").val('');
                       } else {
                          $("#state_license_expiry"+row_id).val('');
                       }

                       /*if(row_id == ''){
                          $("#dea_license_id").val('');
                          $("#dea_license_id").prop('readonly',false);
                       } else {
                          $("#dea_license_id_"+row_id).val('');
                          $("#dea_license_id_"+row_id).prop('readonly',false);
                       }*/

                       if(row_id == ''){
                          $("#shipping_street").val('');
                          $("#shipping_street").prop('readonly',false);
                       } else {
                          $("#shipping_street_"+row_id).val('');
                          $("#shipping_street_"+row_id).prop('readonly',false);
                       }

                       if(row_id == ''){
                          $("#shipping_city").val('');
                          $("#shipping_city").prop('readonly',false);
                       } else {
                          $("#shipping_city_"+row_id).val('');
                          $("#shipping_city_"+row_id).prop('readonly',false);
                       }

                       if(row_id == ''){
                          $("#shipping_state").val('');
                          $("#shipping_state").attr('disabled',false);
                       } else {
                          $("#shipping_state_"+row_id).val('');
                          $("#shipping_state_"+row_id).attr('disabled',false);
                       }

                       if(row_id == ''){
                          $("#shipping_zip").val('');
                          $("#shipping_street").prop('readonly',false);
                       } else {
                          $("#shipping_zip_"+row_id).val('');
                          $("#shipping_zip_"+row_id).prop('readonly',false);
                       }

                        var options = {
                         type: 'popup',
                         title: '',
                         responsive: true,
                         innerScroll: false,
                         clickableOverlay: false,
                         buttons: [{
                             text: $.mage.__('Close'),
                             class: 'success-notifications',
                             click: function() {
                                 this.closeModal();
                             }
                         }]
                     };

                     /*$('#register-success').html(json['msg']);*/
                     $('#register-success').html('<div class="sucess-over-popup"><i class="far fa-times-circle icon-popup-reject"></i><div class="sucess-popup"><span>Invalid state License. Please provide a valid state license</span></div></div>');

                     var popup = modal(options, $('#register-success'));
                     $("#register-success").modal("openModal");

                      }
                    } else {
                      var options = {
                         type: 'popup',
                         title: '',
                         responsive: true,
                         innerScroll: false,
                         clickableOverlay: false,
                         buttons: [{
                             text: $.mage.__('Close'),
                             class: 'success-notifications',
                             click: function() {
                                 this.closeModal();
                             }
                         }]
                     };

                     /*$('#register-success').html(json['msg']);*/
                     $('#register-success').html('<div class="sucess-over-popup"><i class="far fa-times-circle icon-popup-reject"></i><div class="sucess-popup"><span>Invalid state License. Please provide a valid state license</span></div></div>');

                     var popup = modal(options, $('#register-success'));
                     $("#register-success").modal("openModal");
                    }
                   },
                   error: function(xhr, ajaxOptions, thrownError) {
                       alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                   }
                 });
              });
          <?php } ?>

            var other_address_row = <?php echo $other_address_row; ?>;

            $('.add-shipping-address').click(function() {
              html = '<div id="shipping-address-row-' + other_address_row + '">';
               html += '<input type="hidden" id="other_address_id_' + other_address_row + '" name="other_address[' + other_address_row + '][address_id]" value="">';
               html += '<input type="hidden" id="state_license_id_' + other_address_row + '_row" name="other_address[' + other_address_row + '][row_id]" value="' + other_address_row + '">';
               html += '<input type="hidden" id="state_license_status_' + other_address_row + '" name="other_address[' + other_address_row + '][state_license_status]" autocomplete="off" value="">';
                html += '<div class="drl-hr-line"></div>';
                html += '<div class="drl-billing-add-form">';
                  html += '<div class="drl-bill-head">';
                    html += '<legend class="drl-legends-second">';
                      html += '<span class="drl-main-middle-head">Additional Shipping Address </span>';
                    html += '</legend>';
                  html += '</div>';
                  html += '<div class="drl-switch-add-bill"><div class="drl-switch-field"><button type="button" data-toggle="tooltip" title="Remove" class="remove-address-block btn btn-danger"><i class="fa fa-minus-circle"></i></button></div></div>';
                html += '</div>';
                html += '<div class="drl-hr-line"></div>';
                html += '<div class="drl-register">';
                  html += '<div class="field field-state_license_id drl-width-input">';
                    html += '<label class="label drl-required-astr" for="state_license_id"><span>State License Id</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="state_license_id_' + other_address_row + '" name="other_address[' + other_address_row + '][state_license_id]" autocomplete="off" value="" class="validate-medpro-license drl-register-input input-text required" placeholder="Enter State License Id">';
                    html += '</div>';
                  html += '</div>';

                  html += '<div class="field field-dea_license_id drl-width-input">';
                    html += '<label class="label" for="dea_license_id"><span>DEA License Id</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="dea_license_id_' + other_address_row + '" name="other_address[' + other_address_row + '][dea_license_id]" value="" class="drl-register-input input-text" placeholder="DEA License Id">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field  field-state_license_upload drl-width-input">';
                    html += '<label class="label drl-required-astr" for="state_license_upload"><span>Upload State License</span></label>';
                    html += '<div class="control">';
                      html += '<input type="file" id="state_license_upload_' + other_address_row + '" name="other_address[' + other_address_row + '][state_license_upload]" value="" class="drl-register-input input-file required">';
                      html += '<input type="hidden" id="state_license_upload_value" name="state_license_upload_value" value="">';
                    html += '</div>';
                  html += '</div>';
                  html += '<div class="field  field-dea_license_upload drl-width-input">';
                    html += '<label class="label" for="dea_license_upload"><span>Upload DEA License</span></label>';
                    html += '<div class="control">';
                      html += '<input type="file" id="dea_license_upload_' + other_address_row + '" name="other_address[' + other_address_row + '][dea_license_upload]" value="" class="input-file drl-register-input">';
                      html += '<input type="hidden" id="dea_license_upload_value" name="dea_license_upload_value" value="">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field field-legal_business_name drl-width-input">';
                    html += '<label class="label drl-required-astr" for="legal_business_name"><span>State License Expire</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="state_license_expiry_' + other_address_row + '" name="other_address[' + other_address_row + '][state_license_expiry]" autocomplete="off" value="" readonly class="drl-register-input input-text" placeholder="Enter State License Expire Date">';
                    html += '</div>';
                  html += '</div>';
                  html += '<div class="field field-dea_license_expiry drl-width-input">';
                    html += '<label class="label" for="dea_license_expiry"><span>DEA License Expire Date</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="dea_license_expiry_' + other_address_row + '" name="other_address[' + other_address_row + '][dea_license_expiry]" value="" class="dea_datepicker drl-register-input input-text" placeholder="DEA License Expire Date">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field field-shipping_street drl-width-input">';
                    html += '<label class="label drl-required-astr" for="shipping_street"><span>Primary Street (No P. O. Boxes)</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="shipping_street_' + other_address_row + '" name="other_address[' + other_address_row + '][street]" value="" class="drl-register-input input-text required" placeholder="Primary Street (No P. O. Boxes)">';
                    html += '</div>';
                  html += '</div>';
                  html += '<div class="field field-shipping_city drl-width-input">';
                    html += '<label class="label drl-required-astr" for="shipping_city"><span>City</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="shipping_city_' + other_address_row + '" name="other_address[' + other_address_row + '][city]" value="" class="drl-register-input input-text required" placeholder="Enter City">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field field-shipping_state drl-width-input">';
                    html += '<label class="label drl-required-astr" for="shipping_state"><span>State</span></label>';
                    html += '<div class="control">';
                        html += '<select id="shipping_state_' + other_address_row + '" name="other_address[' + other_address_row + '][state]" class="drl-register-input input-text required">';
                          html += '<option value="">Please select a region, state or province.</option>';
                            <?php foreach($block->getRegionsOfCountry('US') as $idx=>$region){ ?>
                                <?php if($idx > 0) { ?>
                                    html += '<option value="<?php echo $region['value']; ?>"><?php echo $region['label']; ?></option>';
                                <?php } ?>
                            <?php } ?>
                          html += '</select>';
                        html += '</div>';
                    html += '</div>';
                    html += '<div class="field field-shipping_country drl-width-input">';
                      html += '<label class="label drl-required-astr" for="shipping_country"><span>Country</span></label>';
                      html += '<div class="control">';
                        html += '<select id="shipping_country_' + other_address_row + '" name="other_address[' + other_address_row + '][country]" class="drl-register-input input-text required">';
                          html += '<option value="US" selected="">United States</option>';
                        html += '</select>';
                      html += '</div>';
                    html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field field-shipping_zip drl-width-input-half">';
                    html += '<label class="label drl-required-astr" for="shipping_zip"><span>ZIP/Postal Code</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="shipping_zip_' + other_address_row + '" name="other_address[' + other_address_row + '][zip]" value="" minlength="5" maxlength="5" class="drl-register-input input-text required validate-zip-us validate-digits" placeholder="Enter ZIP/Postal Code">';
                     html += '</div>';
                  html += '</div>';
                  html += '<div class="field field-shipping_telephone drl-width-input-half">';
                    html += '<label class="label drl-required-astr" for="shipping_telephone"><span>Phone Number</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="shipping_phone_' + other_address_row + '" name="other_address[' + other_address_row + '][phone]" value="" class="drl-register-input input-text required validate-digits" minlength="10" maxlength="10" placeholder="Enter Phone Number">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';

                html += '<div class="drl-register">';
                  html += '<div class="field field-shipping_fax drl-width-input-half">';
                    html += '<label class="label" for="shipping_fax"><span>FAX Number</span></label>';
                    html += '<div class="control">';
                      html += '<input type="text" id="shipping_fax_number_' + other_address_row + '" name="other_address[' + other_address_row + '][fax]" value="" class="drl-register-input input-text validate-digits" placeholder="Enter FAX Number">';
                    html += '</div>';
                  html += '</div>';
                html += '</div>';


                /*html += '  <div class="remove-btn-block"><button type="button" data-toggle="tooltip" title="Remove" class="remove-address-block btn btn-danger"><i class="fa fa-minus-circle"></i></button></div>';*/
              html += '</div>';

              $('#shipping-address-block').append(html);

              $('.dea_datepicker').datepicker({
                  minDate: 0,
                  prevText: '&#x3c;zurück', prevStatus: '',
                  prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                  nextText: 'Vor&#x3e;', nextStatus: '',
                  nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                  monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                      'July', 'August', 'September', 'October', 'November', 'December'],
                  monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                  dayNames: ['Sunday ', 'Monday', 'Tuesday ', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                  dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                  dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                  showMonthAfterYear: false,
                  dateFormat: 'yy-m-d'
              });

              other_address_row++;
            });


            $(".remove-address-block" ).live( "click", function() {
              $(this).parent().parent().parent().parent().remove();
            });

              $(function() {
                $("input[type='radio']").change(function(){
                    if ($(this).val() == 'yes') {
                        $('#showstore').show();
                    }
                    else {
                        $('#showstore').hide();
                    }
                });
              });

        });
        require(["jquery", "mage/calendar"], function ($) {
          $(document).ready(function () {
            $('.dea_datepicker').datepicker({
                minDate: 0,
                prevText: '&#x3c;zurück', prevStatus: '',
                prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                nextText: 'Vor&#x3e;', nextStatus: '',
                nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'],
                monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                dayNames: ['Sunday ', 'Monday', 'Tuesday ', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                showMonthAfterYear: false,
                dateFormat: 'yy-m-d'
            });
          });
        });

     $(document).ready(function(){
        $(".drl-with-coun").intlTelInput({
          initialDialCode: true,
          americaMode: false,
          onlyCountries: ["us"]

        });
      });
    $(window).scroll(function() {
        $("#oval-assit").css("top", Math.max(100, 200 - $(this).scrollTop()));
    });
   });
// Number Validation Start

   // Number Validation End
</script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Terms and Conditions',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: 'drl-term-condition',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#termcon").live( "click", function() {
                $("#popup-modal").modal("openModal");
            });

        }
    );
</script>

