<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>

<?php  $_order = $block->getOrder() ?>
<div class="actions-toolbar">
    <!--<?php if ($_order->getTracksCollection()->count()) : ?>
        <?= $block->getChildHtml('track-all-link') ?>
    <?php endif; ?>-->
    <a href="<?= $block->escapeUrl($block->getPrintAllShipmentsUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $block->escapeHtml(__('Print All Shipments')) ?></span>
    </a>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment) : ?>
    <?= $block->getCommentsHtml($_shipment) ?>
    <div class="order-title">
        <?php if($block->getSapDeliveryId($_shipment->getId())) { ?>
            <strong><?= $block->escapeHtml(__('Shipment #')) ?> <?= $block->escapeHtml($block->getSapDeliveryId($_shipment->getId())) ?></strong>
        <?php } else { ?>
            <strong><?= $block->escapeHtml(__('Shipment #')) ?> <?= $block->escapeHtml($_shipment->getIncrementId()) ?></strong>
        <?php } ?>
        <a href="<?= $block->escapeUrl($block->getPrintShipmentUrl($_shipment)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print Shipment')) ?></span>
        </a>
        <!--<a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($_shipment)) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
           class="action track">
            <span><?= $block->escapeHtml(__('Track this shipment')) ?></span>
        </a>-->
    </div>
    <?php $tracks = $_shipment->getTracksCollection(); ?>
    <?php  if ($tracks->count()) : ?>
        <dl class="order-tracking" id="my-carrier-table-<?= (int) $_shipment->getId() ?>">
            <dt class="tracking-title">
                <?= $block->escapeHtml(__('Carrier Name(s):')) ?>
            </dt>
            <dd class="tracking-content">
                <?php
                $carrier_name = [];
                foreach ($tracks as $track) :
                    $carrier_name[] = $track->getTitle();
                endforeach;
                $carrier_name = array_unique($carrier_name);
                //echo '<pre>'.print_r($carrier_name, true).'</pre>';
                echo implode(",",$carrier_name);
                ?>
            </dd>
        </dl>
        <dl class="order-tracking" id="my-tracking-table-<?= (int) $_shipment->getId() ?>">
            <dt class="tracking-title">
                <?= $block->escapeHtml(__('Tracking Number(s):')) ?>
            </dt>
            <dd class="tracking-content">
                <?php
                $i = 1;
                $_size = $tracks->count();

                foreach ($tracks as $track) : ?>
                    <?php if ($track->isCustom()) : ?>
                        <?= $block->escapeHtml($track->getNumber()) ?>
                    <?php else : ?>
                        <a href="#"
                            data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($track)) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                            class="action track"><span><?= $block->escapeHtml($track->getNumber()) ?></span>
                            </a>
                    <?php endif; ?>
                    <?php if ($i != $_size) : ?>, <?php endif; ?>
                    <?php $i++;
                endforeach; ?>
            </dd>
        </dl>
    <?php  endif; ?>
    <div id="drl-track-form">
        <ul id="drl-progress">
            <li class="drl-bub-track active">Order Created</li>
            <li class="drl-bub-track active">Order Confirmed</li>
            <li class="drl-bub-track active">Out for Delivery</li>
            <li class="drl-bub-track active">Delivered</li>
            <li class="drl-bub-track vechfly "></li>
        </ul>
    </div>
    <?php $podDetails = $block->getPodDetails($_shipment->getId()) ?>
    <?php if($podDetails) : ?>
        <dl class="order-pod" id="pod-table-<?= (int) $_shipment->getId() ?>">
            <?php if($podDetails['pod_date']) : ?>
                <dt class="pod-date-title"><?= __('POD date & time (EST):') ?> </dt>
                <dd class="pod-date-content">
                    <?= $podDetails['pod_date']; ?>
                    <?php if($podDetails['pod_time']) : ?>
                        <?= $podDetails['pod_time']; ?>
                    <?php endif; ?>
                </dd>
            <?php endif; ?>
            <?php if($podDetails['tracking_link']) : ?>
            <dt class="pod-track-link-title"><?= __('Tracking URL:') ?> </dt><dd class="pod-track-link-content"><a href="<?= $podDetails['tracking_link']; ?>" target="_blank"><?= $podDetails['tracking_link']; ?></a></dd>
            <?php endif; ?>
        </dl>
    <?php endif; ?>
    <div class="table-wrapper order-items-shipment">
        <table class="data table table-order-items shipment" id="my-shipment-table-<?= (int) $_shipment->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Shipped')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $block->escapeHtml(__('NDC')) ?></th>
                    <th class="col qty"><?= $block->escapeHtml(__('Qty Shipped')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_shipment->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <?php //echo '<pre>'.print_r($_item->getData(), true).'</pre>'; ?>
                    <?php if($_item->getQty() > 0) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
<?php endforeach; ?>
