<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_loggedin = $this->helper('Magento\Checkout\Helper\Cart')->getCart()->getCustomerSession()->isLoggedIn();
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $StockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$application_verified_status = false;

 if ($customerSession->isLoggedIn()) {

    $customerRepository = $objectManager->get('\Magento\Customer\Api\CustomerRepositoryInterface');
    $_eavConfig = $objectManager->get('\Magento\Eav\Model\Config');

    if($customerSession->getId()) {

        $customerData= $customerRepository->getById($customerSession->getId());

        $attribute = $_eavConfig->getAttribute('customer', 'application_status');
        $options = $attribute->getSource()->getAllOptions();
        $application_statuses = [];
        foreach ($options as $option) {
            if ($option['value'] > 0) {
                $application_statuses[$option['value']] = $option['label'];
            }
        }
        $application_status = 0;
        $approved_id = array_search("Approved",$application_statuses);
        if($customerData->getCustomAttribute('application_status')){
            $application_status = $customerData->getCustomAttribute('application_status')->getValue();
        }

        if($approved_id == $application_status){
            $application_verified_status = true;
        }
    }
}
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Featured products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Featured products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
            <ol class="products list items product-items" id="<?php echo $type;?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?= /* @escapeNotVerified */ $available ?>">
                    <?php if ($showAddTo): ?>
                        <?php if($application_verified_status){ ?>
                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                <?php endif; ?>
                            </div>
                        <?php } ?>
                    <?php endif; ?>
                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <?php
                        $_productNameLength = strlen($block->escapeHtml($_item->getName()));

                        if($_productNameLength < 57){
                            $_productName = $block->escapeHtml($_item->getName());
                        } else {
                            $_productName = substr($block->escapeHtml($_item->getName()), 0, 55).'...';
                        }
                    ?>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                            <?=  $_productName; ?></a>

                        <div class="drl-sku-cashback-attribute"></strong><?= $block->escapeHtml(__('NDC:')) ?> <span class="drl-sku-product product-attribute-sku-<?php echo $_item->getId(); ?>"><?= /* @noEscape */ $_helper->productAttribute($_item, $_item->getSku(), 'sku') ?></span><br />
                        </div>
                        <?php if($application_verified_status){ ?>
                            <div class="drl-sku-cashback-attribute-second">
                                <span class="product-available-stock drl-cashback-stock">
                                    Available: <span id="product-available-qty-value-<?php echo $_item->getSku(); ?>">
                                    <?php if($_item->getTypeId() == 'simple') { 
                                        $salable_quantities = $StockState->execute($_item->getSku());
                                         echo $salable_quantities[0]['qty'];
                                         }?></span>
                                </span>
                            </div>
                        <?php } ?>
                        <?php if($_helper->productAttribute($_item, $_item->getStrength(), 'strength')) { ?>
                            <div class="drl-sku-cashback-attribute-second">
                                <div class="attribute-pack-size">
                                    <div class="swatch-attribute pack_size" >
                                        <span class="swatch-attribute-label">Total Content: </span>
                                        <span class="swatch-attribute-value"><?php echo $_item->getResource()->getAttribute('strength')->setStoreId(0)->getFrontend()->getValue($_item); ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <?php if($_helper->productAttribute($_item, $_item->getPackSize(), 'pack_size')) { ?>
                            <div class="drl-sku-cashback-attribute-second">
                                <span class="swatch-attribute-label">Pack Size</span>
                                <div class="drl-attribute-strength">
                                    <?php echo $_item->getResource()->getAttribute('pack_size')->setStoreId(0)->getFrontend()->getValue($_item); ?>
                                </div>
                            </div>
                        <?php } ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>

                        <?php if ($_item->isAvailable()):?>
                            <?= $block->getProductDetailsHtml($_item) ?>
                        <?php endif; ?>
                       <div class="drl-cash-back">
                            <span class="product-attribute-case-pack">
                                Case Pack&nbsp;<span id="product-case-pack-<?php echo $_item->getId(); ?>"><?= /* @noEscape */ $_helper->productAttribute($_item, $_item->getCasePack(), 'case_pack') ?></span>
                            </span>
                        </div>
                        <?php if($application_verified_status){ ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <div class="field choice related">
                                        <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                        <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if($salable_quantities[0]['qty'] > 0){ ?>                     
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    <?php } ?>                        
                                </div>
                            <?php endif; ?>
                        <?php } ?>
                    </div>
                </div>
                <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
<script>
(function  () {
    require([
        'jquery',
        'Magento_PageBuilder/js/resource/slick/slick',
        'jquery/jquery-migrate'
    ],function($, slick) {
        jQuery(document).ready(function() {
            if($('#related').length > 0) {
                $('#related').slick({
                    dots: false,
                    autoplay:false,
                    infinite: true,
                    variableWidth: false,
                    arrows: true,
                    speed: 500,
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    responsive: [{
                    breakpoint: 600,
                    settings: {
                        arrows: true,
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 400,
                    settings: {
                        arrows: true,
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                }
            ]
                });
            }
        });
    });
})();
</script>